### ISSUE TITLE
Problem: Fixity fails for uncompressed, replicated AIPs created with am 1.10

### ISSUE THREAD

**Issue by amayita** [archivematica/Issues#1209] opened 2020-05-12 18:11 UTC
Edit to Add: 
Connects to https://github.com/artefactual/archivematica-storage-service/pull/544

Fixity fails for uncompressed, replicated AIPs created with am 1.10. 
It continues to fail for legacy AIPs that were ingested with am-1.10, even after upgrading to am-1.11

**Summary:** Fixity and replicated AIPS
```
am-version   Compressed      Uncompressed
1.10              works         FAILS
1.11              works         works
```

**Steps to reproduce**
I have set up a test environment as we are seeing this issue in a client. I have:
* set up an **am-1.10 server with ss-0.15**
* set up an AIP storage pipeline with an associated replicator (replicated AIP storage) pipeline.
* ingested a Sample transfer (archivematica-sampledata/SampleTransfers/Images) twice:
   * Once compressed
   * Once uncompressed
* run fixity-cron
* upgraded to **am-1.11 and ss-0.16**

**Locations**
![Screenshot_2020-05-11_Archivematica_Storage_Service-1-](https://user-images.githubusercontent.com/958745/81728839-5bd0d880-948b-11ea-9634-7600fac1f1ea.png)

**Packages**
![Screenshot_2020-05-11_Archivematica_Storage_Service](https://user-images.githubusercontent.com/958745/81728820-51aeda00-948b-11ea-9001-23199c6c18df.png)

**Expected behaviour**
I expected fixity to succeed :)

**Current behaviour**
Fixity fails:

**archivematica 1.10**
```
Fixity report:
[2020-05-11 18:27:42 UTC] Fixity scan starts at amaya-am-fixity
[2020-05-11 18:27:44 UTC] Fixity scan succeeded for AIP: 0b7e6550-5df6-4527-86e1-c9ac0b4c220a
[2020-05-11 18:27:46 UTC] Fixity scan succeeded for AIP: 1f1fe584-082a-438b-ac0c-59d0d56b2984
[2020-05-11 18:27:47 UTC] Fixity scan succeeded for AIP: 48c820d4-8c62-4c2c-bd3a-543fbe94ea47
[2020-05-11 18:27:47 UTC] Storage service at "http://51.89.119.158:8000/" encountered an internal error while scanning AIP 2e4ac5f1-bce5-4f58-8287-2a361a3f058e
[2020-05-11 18:27:47 UTC] Successfully scanned 4 AIPs
[2020-05-11 18:27:47 UTC] Fixity scan finished
```
`
0b7e6550-5df6-4527-86e1-c9ac0b4c220a -> /var/archivematica/sharedDirectory/www/AIPsStore/0b7e/6550/5df6/4527/86e1/c9ac/0b4c/220a/Fixity-rep-bug-am-1.10-0b7e6550-5df6-4527-86e1-c9ac0b4c220a.7z` Parent, compressed
`
1f1fe584-082a-438b-ac0c-59d0d56b2984 -> /var/archivematica/sharedDirectory/www/AIPsStore_Rep/1f1f/e584/082a/438b/ac0c/59d0/d56b/2984/Fixity-rep-bug-am-1.10-1f1fe584-082a-438b-ac0c-59d0d56b2984.7z` Replicated, compressed
`
48c820d4-8c62-4c2c-bd3a-543fbe94ea47 -> /var/archivematica/sharedDirectory/www/AIPsStore/48c8/20d4/8c62/4c2c/bd3a/543f/be94/ea47/uncompressed-48c820d4-8c62-4c2c-bd3a-543fbe94ea47` Parent, uncompressed

`2e4ac5f1-bce5-4f58-8287-2a361a3f058e -> /var/archivematica/sharedDirectory/www/AIPsStore_Rep/2e4a/c5f1/bce5/4f58/8287/2a36/1a3f/058e/uncompressed-2e4ac5f1-bce5-4f58-8287-2a361a3f058e` **Replicated, uncompressed, FAILS**

**archivematica 1.11**
```
Fixity report:
[2020-05-11 19:05:48 UTC] Fixity scan starts at amaya-am-fixity
[2020-05-11 19:05:51 UTC] Fixity scan succeeded for AIP: 0b7e6550-5df6-4527-86e1-c9ac0b4c220a
[2020-05-11 19:05:53 UTC] Fixity scan succeeded for AIP: 1f1fe584-082a-438b-ac0c-59d0d56b2984
[2020-05-11 19:05:53 UTC] Fixity scan succeeded for AIP: 48c820d4-8c62-4c2c-bd3a-543fbe94ea47
[2020-05-11 19:05:53 UTC] Storage service at "http://51.89.119.158:8000/" encountered an internal error while scanning AIP 2e4ac5f1-bce5-4f58-8287
-2a361a3f058e
[2020-05-11 19:05:53 UTC] Fixity scan succeeded for AIP: c2b7dbf6-6967-40c8-8fe0-65f4ad88033a
[2020-05-11 19:05:53 UTC] Fixity scan succeeded for AIP: 793c0298-ca2f-47a1-84de-c60044ec9f0f
[2020-05-11 19:05:53 UTC] Fixity scan succeeded for AIP: 7211f461-dc2a-4a38-9456-5b60814029ab
[2020-05-11 19:05:53 UTC] Successfully scanned 7 AIPs
[2020-05-11 19:05:53 UTC] Fixity scan finished
```
Thanks!

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment] 2020-05-13 13:21
Good find! Related to https://github.com/archivematica/Issues/issues/1054#issuecomment-574691035. Specifically the summary of that comment, is that the fixity endpoint wraps bag-check, and while the bag created by either `1.10` or prior, and `1.11` is not invalid, the additional structure created for uncompressed replicas in `1.10` means that the bag check is being pointed to the wrong location:
```
    └── 150f
        └── 10a-98667415-6ac6-489b-b192-779c3cc1150f   <--- We start here...
            └── 10a-a9d2726c-51a9-4361-bd6e-1e0f8eeb0435   <--- Bag starts here...
                └── data
```
With the fix for 1054 we didn't put in place a mechanism to correct the `1.10` structure, nor make the check versioned or more resilient i.e. check for the different structure and handle that accordingly.

**Comment by tw4l** [comment] 2020-11-12 19:58
Replicas of legacy AIPs created in AM 1.10 can now be re-created by running the Storage Service management command `create_aip_replicas` introduced in https://github.com/artefactual/archivematica-storage-service/pull/544 with the `--delete` option, which will delete existing replicated AIPs before creating new ones.

**Comment by ross-spencer** [comment] 2020-12-08 19:10
Performing some impromptu QA on the replication fix for this today as I use it to understand some of the implications for https://github.com/archivematica/Issues/issues/985 I notice that when using the `--delete` argument the deletion is completed without the creation of an 'event' in the storage service logs which would then be visible in the UI. For the deletion of a replicated package under normal circumstances a user would write their reason for deletion and then that would be recorded once the deletion was confirmed. Does the management task need to leave an audit trail behind as well? cc. @sromkey @tw4l

**Comment by tw4l** [comment] 2020-12-11 03:04
@ross-spencer Thanks, that's a good catch! I suspect it would be ideal to register an event recording the reason for deletion.

QA of this command by support identified that the presence of deleted AIPs in the Storage Service database was preventing hte command from working as expected, a problem which is fixed by https://github.com/artefactual/archivematica-storage-service/pull/552. Since this is related to a client support need, I thought it better to submit that PR quickly, but if @sromkey agrees on the importance of leaving an audit trail with the reason for deletion behind, I'd be happy to plan to work on an additional PR with that functionality as time allows.

**Comment by sromkey** [comment] 2020-12-23 16:35
Sorry for the delay reading this!!
I'm sort of the mind that when it comes to replicas they don't need to be treated quite the same as the original AIP... so if in the workflow the original AIP is unchanged I don't have a problem deleting and replacing replicas without the audit log.  Let me know if I seem to be misunderstanding though...

**Comment by tw4l** [comment] 2021-01-11 21:59
PR https://github.com/artefactual/archivematica-storage-service/pull/552 has been merged, but I am retaining the dev branch for now since @amayita is continuing to use it in support for the next week or so. I will delete it after she lets me know that it's safe to do so.

**Comment by tw4l** [comment] 2021-01-12 20:26
Dev branch has now been deleted^

**Comment by ablwr** [comment] 2021-04-05 20:11
Is this issue all set/resolved? What do you think, @amayita?

**Comment by amayita** [comment] 2021-04-06 16:38
Yes, please feel free to close the issue as "solved".

**Comment by ablwr** [comment] 2021-04-06 16:40
@sromkey Is there a specific process for that? I can't keep up

**Comment by sromkey** [comment] 2021-04-12 13:29
Sorry, I'm behind in emails/pings. The process hasn't changed- please leave in review for now and we'll close when we do release testing. Thanks!

**Closed** 2021-07-06 14:24 UTC
Labels: Status: review, Type: bug
