### ISSUE TITLE
Problem: PREMIS Agent code doesn't match version

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#662] opened 2019-04-18 21:19 UTC
**Expected behaviour**
For release 1.9.1, the Agent code should match the version.

**Current behaviour**
Version is 1.9.1, Agent code is 1.9.0. This results in the Agent code in the METS file being 1.9.0 instead of 1.9.1.

**Steps to reproduce**
Go to Administration tab and click on Version in the menu; or create an AIP and note the Agent code in the AIP METS file.

**Your environment (version of Archivematica, OS version, etc)**
amdemo 1.9.1

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment] 2019-04-19 11:06
Hi @evelynPM I think @sromkey might be able to elaborate more. My received understanding is that this isn't a documented part of a point release. Because version information is difficult to update and includes a Django migration, we keep the version information at the minor increment, so `1.8.1` would have displayed as `1.8.0` in the METS too. We initially thought there would be little impact to this, but it does create an additional support overhead if a user is having a problem fixed in the point release. 

This is a good ticket to discuss the rationale further and seek a way forward.

There is a qausi-epic that collects together more information and links to tickets describing the difficulties with updating version information in Archivematica. It also collects links to other use-cases such as temporary versioning for developers.

**Comment by evelynPM** [comment] 2019-04-23 13:32
I just checked an AM 1.8.1 instance and the Agent code is 1.8.1.

**Comment by ross-spencer** [comment] 2019-04-23 14:10
Ah, yep, I see, that's stored here: https://github.com/artefactual/archivematica/blob/fe0411be8b34bd2d7f2d49ae4e0fe0e5965e7e9c/src/archivematicaCommon/lib/version.py good spot, thanks @evelynPM.

**Comment by sromkey** [comment] 2019-04-23 14:40
We've been inconsistent about this- it would be good to have better documentation on doing point releases and make a decision about what should be updated and what doesn't need to be.

**Comment by ross-spencer** [comment] 2020-09-17 13:56
Maybe for triage discussion? Spotted this issue while trying to capture some other METS ones, and the issue is related to `1.9`. The same issue doesn't exist in `1.12` right now, e.g.
```xml
<mets:digiprovMD ID="digiprovMD_8">
  <mets:mdWrap MDTYPE="PREMIS:AGENT">
    <mets:xmlData>
      <premis:agent xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
        <premis:agentIdentifier>
          <premis:agentIdentifierType>preservation system</premis:agentIdentifierType>
          <premis:agentIdentifierValue>Archivematica-1.12</premis:agentIdentifierValue>
        </premis:agentIdentifier>
        <premis:agentName>Archivematica</premis:agentName>
        <premis:agentType>software</premis:agentType>
      </premis:agent>
    </mets:xmlData>
  </mets:mdWrap>
</mets:digiprovMD>
```
But the ticket captures a broader process question. Which might also have been solved, so maybe it can just be closed?

**Comment by sromkey** [comment] 2020-09-18 14:14
Ya, good spot @ross-spencer , I think we generally have a process down for this now. I'm going to close.

**Closed by sromkey** 2020-09-18 14:14 UTC
Labels: Ⓜ️ mets/premis
