### ISSUE TITLE
Problem: name of default AIP storage location is awkward

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#1286] opened 2020-08-20 22:04 UTC
**Please describe the problem you'd like to be solved**

The name of the default AIP storage location in Archivematica is "Store AIP in standard Archivematica Directory", which is awkward for two reasons: 1) it's an action statement, rather than a noun, and 2) "standard Archivematica Directory" is ambiguous.

**Describe the solution you'd like to see implemented**

Change it to a noun that specifically refers to the default location in the Archivematica filesystem. Something like "Local AIP storage" could be an option, though that is still fairly ambiguous. Please feel free to throw in suggestions below.

**Describe alternatives you've considered**

This is low priority so we could absolutely leave it as-is.

**Additional context**

This idea came from a discussion on #1214.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by ross-spencer** [comment] 2020-08-20 22:56
This is a duplicate of https://github.com/archivematica/Issues/issues/1271

**Comment by peterVG** [comment] 2020-08-20 23:05
As noted in https://github.com/archivematica/Issues/issues/1214, there is the related issue that the user can change the name of the storage location to better suit their formatting preferences (e.g. from an action statement to a noun). However, if they do, any AIPs that were ingested prior to the name change will continue to use the old label in the "Location" column and any new AIPs, going forward, will use the new label. This also applies to CSV export. This will be misleading to the end users as Archivematica will be using two different names for the same storage location. The user may believe that two different storage locations are being used. 

The solution, it would appear, is to update the Location value in the ElasticSearch index if the Storage Service Location "description" is changed.

**Closed** 2020-08-25 16:21 UTC
Labels: Status: duplicate, Type: enhancement
