### ISSUE TITLE
Problem: inconsistent premis outputs when using File Extension for format identification

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#862] opened 2019-08-15 16:44 UTC
**Expected behaviour**
<premis:formatName> in Object entity should match <premis:eventOutcomeDetailNote> in format identification Event.

**Current behaviour**
In some cases, <premis:formatName> has a value such as "WAV" while <premis:eventOutcomeDetailNote> has "No matching format".

**Steps to reproduce**
Enable File Extension as the format identification tool and ingest *sampleTransfers/Multimedia*.

**Your environment (version of Archivematica, OS version, etc)**

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment] 2020-07-07 11:04
Closing as duplicate of https://github.com/archivematica/Issues/issues/1145 (while #1145 was logged later, it just has a little extra information (and pictures!)) If I have closed this in error, obviously please feel free to re-open.

**Closed by ross-spencer** 2020-07-07 11:04 UTC
Labels: Ⓜ️ mets/premis
