### ISSUE TITLE
Problem: logged-in user not being captured as PREMIS agent

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#529] opened 2019-02-26 01:03 UTC
**Expected behaviour**
There should be three Agents linked to any Event in the AIP METS file: the organization, the software and the logged-in user

**Current behaviour**
I'm only seeing the logged-in user as an Agent for Events that occur when a SIP is generated from a backlogged transfer. Otherwise the Agent is absent.

**Steps to reproduce**
Run a transfer all the way through and check the METS file; or
Run a transfer through to backlog, retrieve from backlog, generate a SIP and run it the rest of the way through, and check the METS file

**Your environment (version of Archivematica, OS version, etc)**
am19centos.qa

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment] 2019-02-26 19:50
I've submitted #1354 to ensure that the new package module we added in AM18 associates the user to the transfer. That should guarantee that events created during transfer have the user agent included.

However, I think it's still possible to have the user agent missing in events created during ingest if the creation of the SIP was automated - but this does not seem to be a regression. This is not addressed by #1354, let me know if that's considered a blocker.

I'm going to test in my local Archivematica 1.6 instance.

**Comment by sevein** [comment] 2019-02-26 20:03
Here's a METS created in Archivematica 1.6: https://gist.github.com/sevein/e2aa58dcb4d1dd6f563ce61bfb78d701. I had to change the processing configuration to be fully automated to reproduce the scenario described in my previous comment.

I think the problem is that Archivematica relies on user interactions happening during processing to associate the user to the package - in a fully automated processing configuration, there are no user events during ingest so the system does not have a chance to associate the user to the SIP. This could be fixed by associating the user during the SIP creation. The solution may require more effort than #1354 because there's more than one way to create a SIP and there's poor code encapsulation in that area, i.e. not just one place that needs to be tweaked.

**Comment by sromkey** [comment] 2019-02-26 20:08
IMO the addition of a user agent in an automated workflow is a different feature, so I'm comfortable with a solution that adds the user agent back into the METS if the AIP is created manually through the dashboard.

**Comment by sevein** [comment] 2019-02-27 23:52
The latest PR (#1357) ensures that all PREMIS events have the associated user agent when the SIP creation is automated via processing config.

**Comment by sevein** [comment] 2019-02-28 01:20
Related: https://github.com/artefactual/archivematica/issues/914.

**Comment by currmie** [comment] 2019-02-28 19:45
On am19xenial, all 3 agents linked to events after retrieving files from backlog, creating SIP, and running transfer all the way through.

**Comment by evelynPM** [comment] 2019-03-01 01:32
Now working on on centos and rpms.

**Closed** 2019-03-06 19:58 UTC
Labels: Severity: critical, Status: verified
