### ISSUE TITLE
Problem: (full) re-ingest failing (related to transaction.atomic)

### ISSUE THREAD

**Issue by jrwdunham** [archivematica/Issues#48] opened 2018-07-31 16:48 UTC
**Expected behaviour**

I should be able to perform a full re-ingest on an AIP.

**Current behaviour**

The re-ingest begins, but fails at "Assign file UUIDs to objects":

<img width="969" alt="screen shot 2018-07-31 at 9 40 02 am" src="https://user-images.githubusercontent.com/2504271/43473991-6ee22672-94a6-11e8-8170-46a01d6c3de6.png">

with:

    An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.Traceback (most recent call last):
      File "/src/MCPClient/lib/job.py", line 102, in JobContext
        yield
      File "/src/MCPClient/lib/clientScripts/assign_file_uuids.py", line 177, in call
        job.set_status(main(**(args)))
      File "/src/MCPClient/lib/clientScripts/assign_file_uuids.py", line 129, in main
        transfer = Transfer.objects.get(uuid=transfer_uuid)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 328, in get
        num = len(clone)
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 144, in __len__
        self._fetch_all()
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 965, in _fetch_all
        self._result_cache = list(self.iterator())
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in iterator
        results = compiler.execute_sql()
      File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
        cursor.execute(sql, params)
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 59, in execute
        self.db.validate_no_broken_transaction()
      File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 327, in validate_no_broken_transaction
        "An error occurred in the current transaction. You can't "
    TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

**Steps to reproduce**

1. Create an AIP.
2. Initiate a full re-ingest (from the SS; the same bug presumably arises when initiated from the Archival Storage tab, but I haven't tested this)
3. Approve the transfer (re-ingest)
4. Wait for the `Assign file UUIDs to objects` and expect to see a failure.

**Your environment (version of Archivematica, OS version, etc)**

- AM qa/1.x (325e792)
- SS qa/0.x
- I have encountered this bug sometimes and sometimes not: exact conditions for re-creation are unknown.

**Comment by sallain** [comment] 2018-10-25 23:31
@sevein Is this actually blocked? I will try to reproduce.

**Comment by sevein** [comment] 2018-10-25 23:45
Yeah, precisely because we haven't been able to reproduce! :thinking:

**Comment by ross-spencer** [comment] 2018-10-26 10:40
I had a brief look this morning. The error described here: https://stackoverflow.com/a/32206432 makes sense if the database connection goes away while trying to add more to it. 

The module hasn't changed since the database batching changes: https://github.com/artefactual/archivematica/blob/d6b004ece75cc359df6a224c477a9f2a49fe74ec/src/MCPClient/lib/clientScripts/assign_file_uuids.py#L171 

I tried to artificially make the script fail by raising exceptions or deliberately passing bad data structures, but our code is otherwise quite robust to when these types of things are happening. If it does fail, it does so quickly and we don't try to write to the database in the same transaction it seems. I tried to make the database go away (or timeout) by running a larger 1000 object transfer through reingest (this feels like something @scollazo encountered early on with the batching changes?). 

The line that seemed to be causing the problem: https://github.com/artefactual/archivematica/blob/d6b004ece75cc359df6a224c477a9f2a49fe74ec/src/MCPClient/lib/clientScripts/assign_file_uuids.py#L129 doesn't seem to have a lot that can go wrong either.

Other than the code making a lot of assumptions, that things will be where we expect them to be! (We don't anticipate too many errors) I can't see where the issue would have arisen. 

That is to say, I can't recreate it either :)

**Comment by sallain** [comment] 2018-10-26 16:15
I also can't reproduce this and it sounds like @ross-spencer's investigation didn't reveal much either (except for the long duration on big reingests - which sounds like something to optimize rather than a directly-related bug). Full reingests seem to be working fine, whether they're triggered from the dashboard or the Storage Service.

**Comment by sallain** [comment] 2018-10-26 16:29
Closing as no one could reproduce this bug.

**Closed by sallain** 2018-10-26 16:29 UTC
Labels: Severity: high, Status: invalid, Type: bug
