### ISSUE TITLE
Problem: Cannot create more than one SIP from a transfer

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#270] opened 2018-10-12 18:07 UTC
**Expected behaviour**
When arranging SIPs from backlog on the Ingest tab, it should be possible to make multiple SIPs from one or more transfer sources, as long as the same files are not included in more than one SIP. 

![screen shot 2018-10-12 at 10 21 01](https://user-images.githubusercontent.com/672121/46885297-67ba6b80-ce0c-11e8-988b-8531d214e4d4.png)

**Current behaviour**

After successfully creating a first SIP, the "Create SIP" option for a second SIP hangs indefinitely, i.e. the spinning wheel to the right runs indefinitely without creating the second SIP.

![screen shot 2018-10-12 at 10 25 20](https://user-images.githubusercontent.com/672121/46885617-59b91a80-ce0d-11e8-8a8d-591eb3420af0.png)

**Steps to reproduce**

1. Create a transfer and send it to backlog (e.g. using "/SampleTransfers/DemoTransfer").
![screen shot 2018-10-12 at 10 01 38](https://user-images.githubusercontent.com/672121/46885822-f5e32180-ce0d-11e8-9f58-5988f6f61632.png)
2. Create two SIP directories under the "arrange" directory on the Ingest tab and add one or two files from the transfer to each one.
3. Select the first SIP and press the "Create SIP" option to create the first SIP.
4. Select the second SIP in the "arrange" pane and press the "Create SIP" option.

**Your environment (version of Archivematica, OS version, etc)**

AM 18x.qa (Bionic), AM 18x.qa (Xenial), AM 17x.qa (Xenial)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment] 2018-10-12 22:20
Confirmed this on 1.7.2 (augustus) but using the Appraisal tab - I can create my first SIP, with two of the objects from my transfer, but when I try to create the second SIP it fails to create. I also tried this on 1.8 (bionic) and experienced the same.

To recreate:

1. Run a transfer through to backlog. In these tests I used the DemoTransfer folder.
2. In the Appraisal tab, search for items in backlog.
3. Using the Arrangement pane, click "Add directory" and create a directory, Dir1.
4. Drag a couple of items from the backlog to Dir1, and then select Dir1 and click **Create SIP**

You should get a green banner with a success message, and Dir1 should disappear from the Arrangement tab.

5. Without refreshing the page, create another new directory, Dir2. Dir2 will not appear in the Arrangement pane.
6. Refresh the page - you will see that Dir1 still exists and that Dir2 is nested inside it. Delete Dir1 (which also deletes Dir2).
7. Create a third new directory, Dir3. There are still items remaining in the backlog from our original transfer. Drag a couple of items from the backlog to Dir3, and then select Dir3 and click **Create SIP**.

A pink banner will appear with the message `SIP could not be started! Check dashboard logs.`

**Comment by sevein** [comment] 2018-10-15 23:14
This was introduced by https://github.com/artefactual/archivematica-storage-service/pull/320/files which introduced the ability to use `rename` (effectively moving) instead of `rsync` (effectively copying) as a performance improvement. The downside is that the originals are not present in the backlog anymore, but they're expected to be. There are mechanisms in place (`SIPArrange`) to hide already transferred items from the backlog, but things like `logs` and `metadata` are not expected to be moved like the new behavior is doing.

The endpoint that we're using in SS is [Move files to this location](https://wiki.archivematica.org/Storage_Service_API#Move_files_to_this_location). It claims that it moves but what I think is that we've been relying on the fact that before https://github.com/artefactual/archivematica-storage-service/pull/320/files it's just being copying.

If this is correct, a potential solution could be to have the endpoint learn a new parameter to disallow moving even when it's possible.

CC @jhsimpson.

**Comment by sallain** [comment] 2018-10-26 20:54
This seems to be working now! I was able to split a transfer into two SIPs without any issue. I didn't even have to refresh the page.

There is a bit of a lag between starting an arranged SIP from the Appraisal tab and the folder that you start the SIP from disappearing from the Arrangement pane, about a minute, but I don't think it's a big deal.

**Closed** 2018-11-22 16:05 UTC
Labels: Severity: high, Status: verified, Type: bug
