### ISSUE TITLE
Problem: Bionic jhove package is newer than artefactual repo one

### ISSUE THREAD

**Issue by mamedin** [archivematica/Issues#1065] opened 2020-01-16 11:35 UTC
**Expected behaviour**

We should use jhove=1.20.1-1~18.04

**Current behaviour**

Bionic installs the latest one from its repository: 1.20.1-5~18.04.1ubuntu1

**Steps to reproduce**

Install archivematica on bionic or upgrade packages.

**Your environment (version of Archivematica, operating system, other relevant details)**

AM1.10.1
Ubuntu Bionic

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment] 2020-01-16 11:37
Workaround is to downgrade the package with:

```
sudo apt-get install jhove=1.20.1-1~18.04 
``` 

But auto-upgrades will upgrade the package later.

**Comment by ablwr** [comment] 2020-01-16 15:03
Will upgrading to an even-later version of JHOVE stop the conflicts with auto-upgrades?

I remember this issue coming up when testing which version of JHOVE to bump us up to, and couldn't use 1.22 because of a similar-or-same error when trying to move to the latest. I filed an issue which ended up being a duplicate of this one, where it was resolved: https://github.com/openpreserve/jhove/issues/502

**Comment by ablwr** [comment] 2020-01-20 17:14
Here's a little more information (and some of these links provide more detailed examples into how JHOVE is behaving).

I want to emphasize that this is affecting every Archivematica instance that uses Ubuntu 18.04 and has auto-updates turned on, which is most users. So the severity of this issue shouldn't be understated. I think anyone using Archivematica in these conditions will have to perform the above rollback. (I have no idea how often these updates happen -- "periodically")

It is only affecting users with JPEGs that contain any [ANSI/NISO metadata](https://www.niso.org/publications/ansiniso-z3987-2006-r2017-data-dictionary-technical-metadata-digital-still-images).

I don't have a test file that I can provide publicly to replicate this issue, but I can point Artefactual staff to where one exists.

It seems that this bug appeared in the above version and still may be present in 1.24-RC, so this doesn't appear to be stable enough to move forward with a fix, but rather we need to stay locked into the above specific version @mamedin mentions. This is likely to be resolved by the time 1.12 is getting ready, so we should consider an upgrade to 1.24 for that release.

Here is a brief history:
Me raising the bug when testing to determine if it was appropriate for Archivematica to upgrade to the then-latest 1.22 version: https://github.com/openpreserve/jhove/issues/459
Someone else raising and patching the bug: https://github.com/openpreserve/jhove/issues/502

Someone else raising a different in 1.22, but should be considered: https://github.com/openpreserve/jhove/issues/456 This issue relates to the relationship between JHOVE and Java, and an auto-update of Java should be considered when making decisions around this issue.

1.22 is the latest official version of JHOVE, given there doesn't seem to have been a 1.23 version, and 1.24 is still listed as a release candidate (releases here: https://github.com/openpreserve/jhove/releases)
 
This issue coming up as tested in the GUI for 1.24, a few days ago:
https://github.com/openpreserve/jhove/issues/558
https://github.com/openpreserve/jhove/issues/559

There also seems to be many PDF-associated bugs found in the 1.24-RC, so I don't think a new version will be right around the corner.

**Comment by ablwr** [comment] 2020-01-20 20:38
Following up on this a bit -- the Jhove 1.24 RC seems to resolve this issue, in the sense that it no longer crashes out. When the RC graduates to a standard release, we can do the analysis work as to whether or not we should upgrade.

By-and-by, general users can test using [this image, which embeds Z39.87 metadata](https://github.com/thisismattmiller/embedmydata.com/blob/master/src/example3.jpg).

**Comment by sromkey** [comment] 2020-07-21 14:33
@mamedin it looks like the PR pins the version of Jhove, in your opinion does that resolve this issue?

**Comment by mamedin** [comment] 2020-07-21 18:43
@sromkey Yes, it fixed the issue. If Ubuntu releases a newer `jhove` package we can always create a new package with higher version or extraversion.

**Closed** 2020-07-21 19:07 UTC
Labels: Type: bug
