### ISSUE TITLE
Problem: the last row of CSV metadata is applied to each object for searching, so most CSV metadata is not searchable and search results are unexpected

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#274] opened 2018-10-16 00:04 UTC
**Expected behaviour**
In the Archival Storage tab, I should be able to search for a digital object by looking for descriptive metadata that is present in the METS file. For example, in [SampleTransfer/DemoTransfer](https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/DemoTransfer), there are four objects with descriptive metadata provided by the [metadata.csv](https://github.com/artefactual/archivematica-sampledata/blob/master/SampleTransfers/DemoTransfer/metadata/metadata.csv). I should be able to find any of them by the contents of the title field (i.e. `14000 Caen, France - Bird in my garden`, `Beihai, Guanxi, China, 1988`.)

**Current behaviour**

After storing an AIP generated from DemoTransfer, searching for any of the titles provided in the metadata.csv results in a failed search (no results found) - except for the last title, `OCR image`. Doing an exact search on this term shows all of the objects from the AIP.

The reason for this is apparent if you look at the raw [JSON output for each file](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1). There are five JSON files available at that link:

* [1-AIP-level.json](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1#file-1-aip-level-json): indexed data for the whole AIP, this file includes the DC metadata for each item
* [2-ocr-image.json](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1#file-2-ocr-image-json): the indexed data for ocr-image.png. [Lines 648-671](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1#file-2-ocr-image-json-L648-L671) show the descriptive metadata attached to this file.
* [3-beihai.json](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1#file-3-beihai-json): the indexed data for beihai.tif. Looking for this file's descriptive metadata, we can see at [lines 1019-1042](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1#file-3-beihai-json-L1019-L1042) that the wrong descriptive metadata has been added - it is the descriptive metadata that belongs to ocr-image.png.
* [4-remarkables.json](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1#file-4-remarkables-json-L699-L722) and [5-bird.json](https://gist.github.com/sallain/f9d34768308781af5c74c0f279f924b1#file-5-bird-json-L742-L765) show the same thing

I've only done a couple of tests but I believe that the descriptive metadata from the **last** row in the CSV is being applied to the digital objects for searching. Therefore, I can't search for the descriptive metadata created for other items at all.

Worth noting (and worthy of more investigation) is that I haven't been able to search on descriptive metadata created through the metadata GUI at all.

**Steps to reproduce**

1. Create an AIP using the DemoTransfer and store it.
2. Perform the following search (note that full search term is `Beihai, Guanxi, China, 1988`):

![beihai-search](https://user-images.githubusercontent.com/4612276/46984428-10c9c600-d09a-11e8-879d-47420155897c.png)

3. Perform another search:

![ocr-image-search](https://user-images.githubusercontent.com/4612276/46984430-13c4b680-d09a-11e8-9a60-b3a410c462cf.png)

4. Review the raw JSON output for the objects, looking in particular at the dmdSec.

**Your environment (version of Archivematica, OS version, etc)**
1.7.2 (Ubuntu Xenial) and 1.8 (Ubuntu Bionic)

Related issue: https://projects.artefactual.com/issues/8081

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by replaceafill** [comment] 2019-01-09 17:30
I think this issue is caused by the way the `METS` file is parsed before indexing it in ElasticSearch. If there are multiple descriptive metadata (`mets:dmdSec`) elements in the XML, only the last one is used (note [how dmdSecData is overwritten in each iteration](https://github.com/artefactual/archivematica/blob/e240825332b76f3cc50b66646921fd9b1ab84d4b/src/archivematicaCommon/lib/elasticSearchFunctions.py#L544-L549)):

```
    # get SIP-wide dmdSec
    dmdSec = root.findall("mets:dmdSec/mets:mdWrap/mets:xmlData", namespaces=ns.NSMAP)
    dmdSecData = {}
    for item in dmdSec:
        xml = ElementTree.tostring(item)
=>      dmdSecData = xmltodict.parse(xml)
```

Then this [`dmdSecData` variable is shared](https://github.com/artefactual/archivematica/blob/stable/1.8.x/src/archivematicaCommon/lib/elasticSearchFunctions.py#L573-L576) as each file is indexed in ElasticSearch:

```
    # establish structure to be indexed for each file item
    fileData = {
        'archivematicaVersion': version.get_version(),
        'AIPUUID': uuid,
        'sipName': sipName,
        'FILEUUID': '',
        'indexedAt': time.time(),
        'filePath': '',
        'fileExtension': '',
        'isPartOf': is_part_of,
        'AICID': aic_identifier,
        'METS': {
=>          'dmdSec': rename_dict_keys_with_child_dicts(normalize_dict_values(dmdSecData)),
            'amdSec': {},
        },
        'origin': get_dashboard_uuid(),
        'identifiers': identifiers,
        'transferMetadata': _extract_transfer_metadata(root),
    }
```
To solve it I think we could query the Structural Map Section element (`structMap`) in each file iteration, looking first for the corresponding `FILEID` and from there the appropriate `dmdSec`. It seems a bit inefficient but I couldn't figure out a better way.

**Comment by sevein** [comment] 2019-01-09 19:01
@replaceafill good detective work. My knowledge on how searches work in Archivematica is very limited. If I understood the problem correctly, we are currently populating `fileData["METS"]["dmdSec"]` in a way that is not efficient and we're only including one of the `dmdSec` elements available but that's just determined by the order in which they appear in the METS document? That said, if you'd be fixing this, you'd be just including the `dmdSec` for that particular file instead? Do we need to include the `dmdSec` of the AIP as a whole too?

I'm going to CC @ross-spencer because I think he may be helpful here. It'd be nice to have Radda take a look too but he's on holidays now.

@replaceafill in the meantime you may want to take a look at this issue: https://github.com/artefactual/archivematica/issues/1199. It's solving a different problem but it's to be aware of it.

**Comment by ross-spencer** [comment] 2019-01-10 15:52
@replaceafill good work indeed. I can confirm the same behavior. All the indexes I can see here when I `view raw` are all the same:

![image](https://user-images.githubusercontent.com/1880412/50979428-b6a09b80-14f6-11e9-8470-6aca2c131843.png)

The only thing I wanted to verify was the potential that this was a regression to see if there was an original intention to the code. Unfortunately it hasn't changed since Archivematica was moved from Sub Version in 2012, the only commit referencing the string:

```
commit cb5f427c9cc3bc5fba8765ad1bd9b27714d4384f
Author: Jesús García Crespo <jesus@sevein.com>
Date:   Fri Sep 14 23:37:51 2012 -0700

    Initial commit (from Subversion repository, r3278).
```

It's hard to tell the author's original intentions, so yep, we've a bug! 

It seems like there are a few ways you can approach implementing your solution, but I think it's the canonical way to make programmatic use of the physical structmap where each entry refers to a unique ID belonging to the dmdsec:
```
<mets:div LABEL="View_from_...in_spring.jpg" TYPE="Item" DMDID="dmdSec_2">
  <mets:fptr FILEID="file-a09e8312-fc4e-4199-a2fd-8bf569d76868"/>
</mets:div>
```
Looking forward to seeing the PR! :+1:

**Comment by sallain** [comment] 2019-02-05 01:22
Searching by CSV metadata now works, which is amazing - I'm so happy @replaceafill!!!

However, there's one thing that concerns me - and that's the raw JSON output. For every file or AIP, clicking on _view raw_ only shows this:

```
{
  "_id": "<some-id-here>", 
  "_index": "aips", 
  "_type": "aip", 
  "found": false
}
```

You can look back up to the original comment on this issue to see what the JSON used to look like. The raw JSON is dubiously helpful from a user's point of view but it was super helpful for me to diagnose a variety of searching issues, so I think we should keep it if possible!.

**Comment by replaceafill** [comment] 2019-02-05 01:52
Ouch, sorry about that @sallain. I'll investigate.

**Comment by jraddaoui** [comment] 2019-02-05 14:22
Thanks @replaceafill and @sallain,

That's definitely a regression from #1171. We should be passing the index name instead of the type after the upgrade. Moreover, this is getting the ES host and using `httplib` to make the request, instead of using the Elasticsearch client like in everywhere else. I'll take care of both things if that's okay for you @replaceafill.

**Comment by jraddaoui** [comment] 2019-02-05 16:55
Hi @sallain, the view raw links should be fixed now in qa/1.x.

**Comment by sallain** [comment] 2019-02-05 18:01
It's fixed, thanks @jraddaoui and @replaceafill!

This ticket's verified!!!

**Closed** 2019-03-06 19:59 UTC
Labels: Status: verified, Type: bug
