### ISSUE TITLE
Problem: Archivematica and the Storage Service do not have audit logging capabilities

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1341] opened 2021-01-14 18:46 UTC
**Please describe the problem you'd like to be solved**
Neither Archivematica nor the Storage Service facilitate logging of user access to the software applications or stored AIPs, transfers, DIPs and other packages. It would be useful to be able to find out who had access to content in the event of a data breach, or simply to be able to demonstrate that the software is secure against unauthorized access, particularly in cloud-hosted environments. Audit logs should be shareable in the Common Event Format (CEF)  

**Describe the solution you'd like to see implemented**
The primary auditing mechanism will be the nginx reverse proxy access logs. Artefactual will add middleware to the Archivematica and Storage Service applications which, when enabled, will add a custom HTTP header with the name of the currently authenticated user to all responses sent from Archivematica and the Storage Service. The nginx access logs will thus include the time, request URL, requester’s IP address, HTTP method, status code, and authenticated user for each activity that happens via the Archivematica and Storage Service web UIs and APIs. As part of this project, Artefactual will also create tooling that takes these nginx access logs and turns them into the CEF format, mapping the information such as URL, HTTP method and status code to semantically meaningful events.

The CEF syslog format, per the ArcSight CEF Implementation Standard (https://community.microfocus.com/t5/ArcSight-Connectors/ArcSight-Common-Event-Format-CEF-Implementation-Standard/ta-p/1645557), is as follows: 

`Timestamp host CEF:Version|Device Vendor|Device Product|Device Version|Signature ID|Name|Severity|Extension` 

A sample event based on this specification would be:

`Dec 17 2020 17:32:15 host CEF:0|Artefactual Systems|Archivematica Storage Service|hosted|15|AIP download|1|src=10.0.0.1 suser=support msg=AIP UUID:e53e9emn-4ffd-42c5-9bfc-541298f4be6c` 

**Describe alternatives you've considered**
Django management commands and other commands issued directly on the application server by technical support or other personnel will not be logged, as those activities don't involve access to AIPs or other packages.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by ross-spencer** [comment] 2021-01-27 18:57
Near-duplicate of https://github.com/archivematica/Issues/issues/351 ? cc. @tw4l

**Comment by tw4l** [comment] 2021-01-27 19:00
Interesting - thanks @ross-spencer !

**Comment by tw4l** [comment] 2021-02-01 22:12
@evelynPM  @ross-spencer I just published [auditmatica](https://github.com/artefactual-labs/auditmatica) on artefactual-labs, which will take Archivematica nginx access logs and turn them into CEF events. That package is now ready for code review.

Based on a closer reading of the [CEF specification](https://community.microfocus.com/t5/ArcSight-Connectors/ArcSight-Common-Event-Format-CEF-Implementation-Standard/ta-p/1645557) as I worked, the resulting CEF events produced by `auditmatica` differ slightly from the specification in this issue description above.

When writing CEF events to a file rather than syslog, the CEF specification instructs to omit the syslog prefix e.g. ("Jan 18 11:07:53 host") and begin the message instead with "CEF:(version)". When writing CEF events to syslog, syslog automatically adds the timestamp when that message was sent. To ensure that the original request time of an event is not lost, I added to the `rt` (request time) extension field by `auditmatica`, along with several other fields that may be useful for auditing purposes, such as request method, request URL, and user agent.

So if our original example in this issue description above was:

```
Dec 17 2020 17:32:15 host CEF:0|Artefactual Systems|Archivematica Storage Service|hosted|15|AIP download|1|src=10.0.0.1 suser=support msg=AIP UUID:e53e9emn-4ffd-42c5-9bfc-541298f4be6c
```

The CEF event written to a file by `auditmatica` actually looks like:

```
CEF:0|Artefactual Systems, Inc.|Archivematica|hosted|16|AIP downloaded from Archival Storage|3|cs1Label=requestClientApplication cs1=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0 rt=Jan 13 2021 20:01:33 requestMethod=GET request=/archival-storage/download/aip/8fa54cfc-f5c5-4673-b44e-fc514496bad7/ src=172.19.0.1 suser=test msg=UUID:8fa54cfc-f5c5-4673-b44e-fc514496bad7
```

And the same CEF event written to syslog (on my machine, named `peregrine`) looks like:
```
Feb  1 17:09:09 peregrine CEF:0|Artefactual Systems, Inc.|Archivematica|hosted|16|AIP downloaded from Archival Storage|3|cs1Label=requestClientApplication cs1=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0 rt=Jan 13 2021 20:01:33 requestMethod=GET request=/archival-storage/download/aip/8fa54cfc-f5c5-4673-b44e-fc514496bad7/ src=172.19.0.1 suser=test msg=UUID:8fa54cfc-f5c5-4673-b44e-fc514496bad7
```

**Closed** 2021-07-05 18:30 UTC
