### ISSUE TITLE
Archivematica Storage-Service and MySQL

### ISSUE THREAD

**Issue by tvdbroek** [archivematica/Issues#1004] opened 2019-11-26 10:30 UTC
**Please describe the problem you'd like to be solved**
When configuring the Archivematica Storage-Service to use MySQL it breaks on the next update.
Currently there is the need to change sqlite to mysql in the Storage-Service code

**Describe the solution you'd like to see implemented**
During install select sqlite or MySQL database for storage-service

**Describe alternatives you've considered**
Building our own repo of Archivematica packages

**Additional context**
This needs to be changed in the following files:
/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/storage_service/storage_service/settings/production.py
line 20
/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/storage_service/storage_service/settings/local.py
line 20

New installations: /etc/default/archivematica-storage-service needs to be configured properly

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes

**Comment by jorikvankemenade** [comment] 2019-11-27 09:56
@tvdbroek just out of curiosity could you elaborate a bit more on what breaks when you use the storage service in combination with MySQL. I am running the storage service with MySQL for quite some time now, and on `0.14`, `0,15` and `qa` I haven't ran into any particular problems so far.

**Comment by tvdbroek** [comment] 2019-11-27 11:05
Hello @jorikvankemenade,
I'm happy to tell you what the issue is i am running in to.
I just upgraded my test environment Storage-Service from 0.14 to 0.15.
Left is the New configuration after upgrading the storage-service
right is the Old configuration

![Screenshot from 2019-11-27 12-01-57](https://user-images.githubusercontent.com/38320466/69718235-223f2780-110e-11ea-9e78-13d328a3a41f.png)

**Comment by scollazo** [comment] 2019-11-27 12:16
You should be able to override the default database settings adding the following environment variable to /etc/sysconfig/archivematica-mcp-client:

```
SS_DB_URL=mysql://storage:ssDBpass@localhost:3306/SS
```

**Comment by jorikvankemenade** [comment] 2019-11-27 12:31
I do what @scollazo does, I add the `SS_DB_URL` to my config and this way you hit the first case in your [config](https://github.com/artefactual/archivematica-storage-service/blob/stable/0.15.x/storage_service/storage_service/settings/production.py#L16). Since my database is on a separate database server and not on localhost, I construct the URL using the following schema:

`mysql://USER:PASSWORD@HOST:PORT/NAME`

This allows the configuration to be flexible. As far as I am aware the Storage Service will eventually move to a MySQL backed, see #952, but this is not officially supported as of yet. However, the `SS_DB_URL` trick is used by many people, it just needs some extra documentation (#784).  For the time being, you can find some information on the connection package [here](https://github.com/jacobian/dj-database-url).

**Comment by tvdbroek** [comment] 2019-11-27 12:51
I have tried the configuration as described above but I'm having issues with it.
That is why i changed the Django back end to MySQL instead of sqlite3.
Have in mind that i use multiple dashboards/MySQL servers load balancers and such.
I will test it again and see what issues i did ran in to

**Comment by jorikvankemenade** [comment] 2019-11-27 13:05
In case it can help you, this is my `/etc/sysconfig/archivematica-storage-service`:

```
# Standard sysconfig for version 0.14 of the Storage Service.
#
# - We set the e-mail settings to use the CERN smtp servers.
# - We set the SS_DB_URL to connect to a DB On Demand server.
# - We increase the number of gunicorn worksers to make sure that the storage
#   service can not freeze when multiple processes are sending requests.
#
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_LANG="en_US.UTF-8"

DJANGO_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DJANGO_STATIC_ROOT=/usr/lib/archivematica/storage-service/assets
DJANGO_SETTINGS_MODULE=storage_service.settings.production
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=cernmx.cern.ch
EMAIL_PORT=25
DEFAULT_FROM_EMAIL=someone@cern.ch
SS_DB_URL=mysql://archivematica:XXXXXXX@dbod-archivematica-dev.cern.ch:5507/SS
DJANGO_ALLOWED_HOSTS=*

SS_GUNICORN_BIND=127.0.0.1:7500
SS_GUNICORN_WORKERS=4

PYTHONPATH=/usr/lib/archivematica/storage-service

REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
```

**Comment by mamedin** [comment] 2019-11-27 14:41
@tvdbroek I could reproduce the issue, it happens when the `/etc/sysconfig/archivematica-storage-service` is changed and reinstalling/upgrading the SS package.

I can confirm it is an issue in the postscript script on `storage-service` Ubuntu packages.

I could fix the issue changing the postscript file and creating a new package. I'll update this issue and I'll create the pull request to am-packbuild later.

**Comment by scollazo** [comment] 2019-11-27 14:45
As a note, this only happens when installing archivematica using debian packages, not with ansible or rpm installs.

**Comment by tvdbroek** [comment] 2019-11-27 14:50
Thanks for the quick replies !
I totally forgot to mention I'm using Ubuntu 16.04 and 18.04 LTS and deploying with the .deb packages.

**Comment by mamedin** [comment] 2019-12-03 19:26
I tried again to test the issue, but this time it doesn't fail. I'll describe step by step how I installed and configured AM with MySQL SS database.

1) Install archivematica in a clean Bionic VM. I used our documentation script:

https://raw.githubusercontent.com/artefactual/archivematica-docs/1.10/admin-manual/installation-setup/installation/scripts/am-bionic-deb.sh

2) Create MySQL SS database and user:

```
sudo cp /etc/mysql/debian.cnf /root/.my.cnf
sudo -H -u root mysql -hlocalhost -udebian-sys-maint -e "DROP DATABASE IF EXISTS SS; CREATE DATABASE SS CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
sudo -H -u root mysql -hlocalhost -udebian-sys-maint -e "CREATE USER 'ss'@'localhost' IDENTIFIED BY 'demo';"
sudo -H -u root mysql -hlocalhost -udebian-sys-maint -e "GRANT ALL ON SS.* TO 'ss'@'localhost';"
sudo -H -u root mysql -hlocalhost -udebian-sys-maint -e "FLUSH PRIVILEGES";
```

3) Configure SS to use database, adding the following to /etc/default/archivematica-storage-service:

```
SS_DB_URL=mysql://ss:demo@localhost:3306/SS
```

Using the above line, all the SS_DB variables are ignored. See: https://github.com/artefactual/archivematica-storage-service/blob/stable/0.15.x/install/README.md

4) Run SS migrations:

```
sudo -u archivematica bash -c " \
set -a -e -x
source /etc/default/archivematica-storage-service
cd /usr/lib/archivematica/storage-service
/usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py migrate";
```

5) Create SS user in MySQL database:

```
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-storage-service || \
        source /etc/sysconfig/archivematica-storage-service \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/lib/archivematica/storage-service
      /usr/share/archivematica/virtualenvs/archivematica-storage-service/bin/python manage.py create_user \
          --username=admin \
          --password=archivematica \
          --email="example@example.com" \
          --api-key="THIS_IS_THE_SS_APIKEY" \
          --superuser";
```

6) Restart Archivematica Storage Service:

```
sudo service archivematica-storage-service restart
```

And that's all.

Then you can try reinstalling the SS:

```
sudo apt-get install --reinstall archivematica-storage-service
```


Anyway, I'm going add the change that fixed the issue when I could reproduce it in this PR:

https://github.com/artefactual-labs/am-packbuild/pull/248

**Comment by sromkey** [comment] 2020-02-18 18:18
If anyone can recreate this we'll re-open but for now we're going to close this based on @mamedin 's previous comment.

**Closed** 2020-02-18 18:19 UTC
Labels: Status: in progress
