### ISSUE TITLE
Problem: replication needs to be more fully documented wrt reingesting or deleting AIPs

### ISSUE THREAD

**Issue by corinnemrogers** [archivematica/Issues#996] opened 2019-11-15 17:50 UTC
**Version of the documentation**
SS 0.15

**Page (and section, if applicable) where the issue occurs**
https://www.archivematica.org/en/docs/storage-service-0.15/administrators/#location-purposes

**Description of the issue**
Documentation doesn't give complete information about the behaviour of replication.

**Suggested fix**
Document that when using replication, deleting an AIP from the AIPstore does not automatically delete the replicated AIP for the replica storage (expected); document that when using replication, reingesting an AIP with changes to the original AIP does not result in the reingested AIP being replicated (known issue #985.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment] 2019-11-18 07:17
Closing as duplicate of https://github.com/archivematica/Issues/issues/685, and logging a reference to that ticket in the description there.

**Closed by ross-spencer** 2019-11-18 07:17 UTC
Labels: Type: documentation
