### ISSUE TITLE
Problem: pressing "Return" keyboard button in Archival Storage search sends previously used term as search input

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#271] opened 2018-10-12 22:38 UTC
**Expected behaviour**
The expected behaviour is that pressing "Return" on your keyboard will act the same as pressing the "Search Archival Storage" button and take the term currently in the search input box as the search term.

**Current behaviour**
The term entered immediately prior to the current term is used as the search input.

**Steps to reproduce**
Go to Archival Storage tab. Leave the search input box blank and press "Search Archival Storage". This will return all items currently available via archival storage search. Enter a more refined search term (e.g. part of a name of an AIP or a file) and press "Return" on your keyboard instead of the "Search Archival Storage" button. This results in returning the results of the original search rather than the more refined search.

**Your environment (version of Archivematica, OS version, etc)**
AM 17x.qa, AM 18x.qa (Bionic, Xenial, Centos)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sallain** [comment] 2018-10-15 18:11
This also occurs if you have previously entered a search term. For example, if I search my AIP store for an AIP called "salamander" by entering the search term and then clicking the search button, it will pull up this result. If I then search for another AIP called "hedgehog" but hit the return key instead of the search button, the search will revert to the term "salamander" and continue to show me the results for my previous search.

**Comment by ross-spencer** [comment] 2018-11-08 14:51
Duplicate of https://github.com/artefactual/archivematica/issues/1044

**Comment by ross-spencer** [comment] 2018-12-18 08:40
This was previously also: https://github.com/artefactual/archivematica/issues/1044 hence the duplication in the 1.9 milestone work last night cc. @sallain @peterVG @sromkey. Closed that one now in favor of this.

**Closed** 2019-03-06 20:00 UTC
Labels: Severity: high, Status: verified
