### ISSUE TITLE
Problem: django database migrations in 1.7 release conflict with qa/1.x versions

### ISSUE THREAD

**Issue by sevein** [archivematica/Issues#54] opened 2018-08-02 21:12 UTC
Compare [1] with [2].
1. https://github.com/artefactual/archivematica/tree/stable/1.7.x/src/dashboard/src/main/migrations
2. https://github.com/artefactual/archivematica/tree/qa/1.x/src/dashboard/src/main/migrations

qa/1.x should have the migrations reordered properly or 1.7 users won't be able to upgrade successfully.

We've have to do a similar task before, see [0f1583](https://github.com/artefactual/archivematica/commit/0f1583) or [457e4e2](https://github.com/artefactual/archivematica/commit/457e4e2).

**Comment by jhsimpson** [comment] 2018-08-10 05:01
This issue is a duplicate of https://github.com/artefactual/archivematica/issues/1011 - I closed that older issue and kept this one open.

**Comment by ablwr** [comment] 2018-10-04 14:36
Has work on this been done? It's marked as Ready but I don't see the corresponding code change.

**Comment by sevein** [comment] 2018-10-04 16:07
Yez! Here: https://github.com/artefactual/archivematica/pull/1236.

The important bit that we've confirmed is that all the migrations in AM17 and AM18 share the same numbering, see below.

```
$ ls src/dashboard/src/main/migrations/
0001_initial.py                                     0025_copyrightstatus_controlled_vocab.py
0002_initial_data.py                                0026_agent_m2m_event.py
0003_archivesspacedipobjectresourcepairing_data.py  0027_full_reingest.py
0003_archivesspacedipobjectresourcepairing.py       0028_version_number.py
0004_rights.py                                      0029_backlog_removal_event.py
0005_reingest_data.py                               0030_rights_import.py
0005_reingest.py                                    0031_job_currentstep_choices.py
0006_levelofdescription.py                          0032_dashboardsetting_scope.py
0007_django_upgrade_tweaks.py                       0033_store_transfer_file_modification_dates.py
0008_fpcommandoutput.py                             0034_add_readme_to_aips.py
0009_matching_gui.py                                0035_fix_workflow_dip_generation.py
0010_dip_upload_store.py                            0036_mediaconch_validation.py
0011_version_number.py                              0037_mediaconch_policy_checks.py
0012_file_id_text.py                                0038_fix_workflow_store_dip.py
0013_upload_archivesspace_inherit_notes.py          0039_delete_sudo_clientscript.py
0014_aic_fixes.py                                   0040_directory_model.py
0015_no_normalize_thumbnails.py                     0041_bind_pids.py
0016_file_currentlocation_nullable.py               0042_directory_uuids_all_transfer_types.py
0017_update_seigfried.py                            0043_remove_create_pointer_file_ms.py
0018_archivesspace_sip_arrange.py                   0044_update_idtools.py
0019_normalization_report.py                        0045_archivesspace_config_dict.py
0020_index_after_processing_decision.py             0046_optional_normative_structmap.py
0021_checksum_algorithms.py                         0047_version_number.py
0022_email_report_args.py                           0048_fix_upload_qubit_setting.py
0023_blob_fields.py                                 0049_change_pointer_file_filegrpuse.py
0024_agenttype.py                                   __init__.py
```

```
$ ls src/dashboard/src/main/migrations/
0001_initial.py                                     0032_dashboardsetting_scope.py
0002_initial_data.py                                0033_store_transfer_file_modification_dates.py
0003_archivesspacedipobjectresourcepairing_data.py  0034_add_readme_to_aips.py
0003_archivesspacedipobjectresourcepairing.py       0035_fix_workflow_dip_generation.py
0004_rights.py                                      0036_mediaconch_validation.py
0005_reingest_data.py                               0037_mediaconch_policy_checks.py
0005_reingest.py                                    0038_fix_workflow_store_dip.py
0006_levelofdescription.py                          0039_delete_sudo_clientscript.py
0007_django_upgrade_tweaks.py                       0040_directory_model.py
0008_fpcommandoutput.py                             0041_bind_pids.py
0009_matching_gui.py                                0042_directory_uuids_all_transfer_types.py
0010_dip_upload_store.py                            0043_remove_create_pointer_file_ms.py
0011_version_number.py                              0044_update_idtools.py
0012_file_id_text.py                                0045_archivesspace_config_dict.py
0013_upload_archivesspace_inherit_notes.py          0046_optional_normative_structmap.py
0014_aic_fixes.py                                   0047_version_number.py
0015_no_normalize_thumbnails.py                     0048_fix_upload_qubit_setting.py
0016_file_currentlocation_nullable.py               0049_change_pointer_file_filegrpuse.py
0017_update_seigfried.py                            0050_remove_magic_links.py
0018_archivesspace_sip_arrange.py                   0051_remove_verify_premis_checksums.py
0019_normalization_report.py                        0052_correct_extract_packages_fallback_link.py
0020_index_after_processing_decision.py             0053_remove_mcp_unused_field.py
0021_checksum_algorithms.py                         0054_index_aip_silent_error_branch.py
0022_email_report_args.py                           0055_normalize_thumbnail_mode_selection.py
0023_blob_fields.py                                 0056_transfer_access_system_id.py
0024_agenttype.py                                   0057_7zip_no_compression.py
0025_copyrightstatus_controlled_vocab.py            0058_fix_unit_variable_pull_link.py
0026_agent_m2m_event.py                             0059_siparrange_longblob.py
0027_full_reingest.py                               0060_delete_orphan_mscl.py
0028_version_number.py                              0061_create_dataverse_transfer_type.py
0029_backlog_removal_event.py                       0062_atom_upload_exit_code.py
0030_rights_import.py                               0063_update_idtools.py
0031_job_currentstep_choices.py                     __init__.py
```

**Closed** 2018-11-22 16:14 UTC
Labels: Severity: high, Status: verified
