### ISSUE TITLE
Problem: pointer file contains mix of Premis 2 and 3

### ISSUE THREAD

**Issue by corinnemrogers** [archivematica/Issues#986] opened 2019-11-12 19:11 UTC
**Expected behaviour**
Pointer file will use Premis 3 exclusively

**Current behaviour**
Pointer file uses Premis 2 in <mets:techMD> and 3 in <mets:digiprovMD>

**Steps to reproduce**
Run a standard transfer and observe the pointer file of the resulting AIP

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.10.1 / SS 0.15

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment] 2019-11-12 19:51
Closing as duplicate of https://github.com/archivematica/Issues/issues/820 (sorry @corinnemrogers I also meant to point that out in Slack last week)

**Closed by ross-spencer** 2019-11-12 19:51 UTC
