### ISSUE TITLE
Problem: Partial re-ingesting AIP with transcribed contents fails on "Move metadata to objects directory"

### ISSUE THREAD

**Issue by ablwr** [archivematica/Issues#498] opened 2019-02-11 20:42 UTC
**Expected behaviour**

A user should be able to re-ingest an AIP that has had the Transcribe Contents microservice performed previously.

**Current behaviour**

When storing the re-ingested AIP, Archivematica fails at the  "Move metadata to objects directory" service. 

**Steps to reproduce**

1 Process folder containing transcribable assets (with an OCR image, for example)
2 Set Transcribe Contents to Yes
3 Select a partial or metadata-only Re-ingest for the AIP (and again transcribe contents)
4 See failure when trying to store the re-ingested AIP under "Move metadata to objects directory" service.

**Your environment (version of Archivematica, OS version, etc)**

0.9x, Ubuntu
(But also 1.7.1, Red Hat)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment] 2019-02-11 23:19
Duplicate of #336

**Closed by sromkey** 2019-02-11 23:19 UTC
