### ISSUE TITLE
Problem: can't arrange a transfer into a new directory that has diacritics in the file name

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#337] opened 2018-11-16 04:12 UTC
**Expected behaviour**
If you create a new directory in the Appraisal tab or on the arrangement widget of the Ingest tab, you should be able to call the new directory whatever you want. The name of the directory becomes the name of the SIP when Create SIP.

**Current behaviour**
If you create a directory on either the Appraisal or Ingest tabs, then add material to it, the directory disappears. You can't recover the directory or the dat and you're no longer able to create any new directories.

**Steps to reproduce**

Appraisal tab:
1. Put some material in backlog
2. On the Appraisal tab, open the Arrangement Pane and click _Add Directory_. Give it a name with a diacritic, like campaña.
3. Drag some material from the backlog pane into the newly-created folder. The folder will disappear.
4. Try to create a new folder.

On 1.7.2, if you look at the Ingest tab and try to expand the "arrange" folder in the arrangement widget, you will see an artifact of the directory.

![screen shot 2018-11-15 at 8 09 18 pm](https://user-images.githubusercontent.com/4612276/48597425-90091e80-e912-11e8-843f-ffbbff46ddc0.png)

You can select this artifact and delete it and everything will reset.

On 1.8, the artifact doesn't appear and I can't figure out if it's possible to reset this from the UI.

**Your environment (version of Archivematica, OS version, etc)**
1.7.2, 1.8

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment] 2020-06-08 15:54
This worth re-testing. (@sallain volunteered to do so!)

**Comment by sromkey** [comment] 2024-08-13 16:45
Just happened upon this issue and I can't reproduce now so closing!

**Closed by sromkey** 2024-08-13 16:45 UTC
Labels: Status: refining, Type: bug
