### ISSUE TITLE
Problem: Can't add rights metadata to ArchivesSpace resource

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#556] opened 2019-03-11 21:42 UTC
**Expected behaviour**
In the ArchivesSpace arrangement pane there is a button to edit rights metadata. Clicking that should open a metadata entry template.

**Current behaviour**
Internal server error occurs when the button is clicked

**Steps to reproduce**
In the ArchivesSpace arrangement pane, select a resource and then click "Edit rights metadata", as per the screenshot below.

![ASpace](https://user-images.githubusercontent.com/14101311/54160011-b136d300-440b-11e9-9cce-3c95bf7e5c33.png)

**Your environment (version of Archivematica, OS version, etc)**

am19centos.qa
---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by smoore4moma** [comment] 2019-05-07 20:32
I didn't realize that Archivematica has ArchivesSpace integrated,  Very interesting.

**Comment by sallain** [comment] 2020-09-25 16:44
Just realized that this is a duplicate of #827. Closing this issue since #827 has a workaround and traceback in the comments.

**Closed by sallain** 2020-09-25 16:44 UTC
