### ISSUE TITLE
Problem: archivematica-storage-service does not use Python 3

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#806] opened 2019-07-19 22:32 UTC
**Please describe the problem you'd like to be solved.**
[archivematica-storage-service](https://github.com/artefactual/archivematica-storage-service) needs to use Python 3 as per the Python 3 [ADR](https://github.com/archivematica/archivematica-architectural-decisions).

**Describe the solution you'd like to see implemented.**
Refactor archivematica-storage-service to use Python 3.

**Additional context**

Python 2.7 final release in July 2020: [here](https://www.python.org/dev/peps/pep-0373/#id5)
Ubuntu 20.04 (LTS) and Python 2.7: [here](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Continue-Py2-Drop)
Python3 may be default in CentOS8/RHEL8: [here](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment] 2019-08-07 05:52
&nbsp;

**Comment by ross-spencer** [comment] 2019-08-07 05:53
SWORD2 issue logged with the repo maintainers: https://github.com/swordapp/python-client-sword2/issues/16 

**NB.** I left https://github.com/archivematica/Issues/issues/806#issuecomment-518950950 blank in-case this ticket becomes its own epic so codetree can modify that field as it needs.

**Comment by ross-spencer** [comment] 2019-12-13 16:47
From internal discussions we have the following gaps in the Py3 migration of the Storage Service:

* Sword2 client library,
* LOCKSS-o-matic model,
* DSpace model.

As such, for `1.11` we will attempt to cherry-pick and merge the pieces of the Storage Service migration that are compatible with both Python 2 and Python 3, and we will continue to run the Storage Service as Python 2 in `1.11.` and try and plug the gaps for `1.12`. 

**Notes on Python 2.7 in 2020:**

Python 2.7 final release in July 2020: [here](https://www.python.org/dev/peps/pep-0373/#id5)
Ubuntu 20.04 (LTS) and Python 2.7: [here](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Continue-Py2-Drop)
Python3 may be default in CentOS8/RHEL8: [here](https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/)

**Comment by sallain** [comment] 2020-02-11 23:39
@ross-spencer I don't think this needs any testing, right? SS in Python 3 is not ready to be run in production, we plan to get it finished and test for the next release.

**Comment by ross-spencer** [comment] 2020-02-12 12:55
Good question @sallain. Definitely nothing we can do around Python 3 here. Where the changes we've made are across the code-base, I don't think there is anything specific. I think some of the more important aspects will be tested through our regression testing. Check-marks below represent things I tested and know Douglas was thinking about as we worked on this, + things we get for free from Travis):

* Storage service can be deployed and migrations are run: ✔️
* Storage service unit tests run: ✔️
* The range of AMAUAT tests run as anticipated (these test both the UI interaction + API): ✔️
* Transfers and integrations work as anticipated: ✔️ (looking promising)

We'll see pretty quickly (imo) if anything strange has been introduced. 

With regards to Github/Kanban mechanics/process, do you want to create a new ticket for that final tranche of storage service work and we can add notes etc. about remaining work? Or keep this open post `1.11`?

**Comment by sallain** [comment] 2020-02-12 17:08
@ross-spencer Okay, perfect - then from a manual tester's perspective, there's nothing specific to do here.

I think it would be best to open a new ticket, so that we can close this one as part of the release; otherwise we'd need to de-milestone which seems odd since work has been done and merged on this issue.

**Comment by ross-spencer** [comment] 2020-03-23 23:35
Closing with note from Slack re: PY3 readiness:
===
I think given the extensive use through testing, and the fact anything works on any of the servers, they can be signed-off. As working baby-steps to Py3 :snake:.

And to answer your question -- Dashboard: unfortunately not because of Gearman. But once the Gearman problem is solved, then theoretically yes. But it's a moving goalpost for now until we commit to making a Py3 virtual environment available (or docker image) in a future release + Gearman 3.

Storage Service - we'd need to fill in those storage service specific gaps first. But it's looking good so far.

**Closed by ross-spencer** 2020-03-23 23:35 UTC
Labels: :snake:³ Python 3, Status: blocked, Status: review

**Comment by ross-spencer** [comment] 2020-03-23 23:36
NB. Complete Py3 readiness will need to be handled in a separate Issue per https://github.com/archivematica/Issues/issues/806#issuecomment-585311263
