### ISSUE TITLE
Upgrade ghostscript across all platforms

### ISSUE THREAD

**Issue by sallain** [archivematica/Issues#439] opened 2019-01-17 19:38 UTC
**Please describe the problem you'd like to be solved.**
The version of ghostscript used in Archivematica is out of date across all environments (9.07 for CentOS/RHEL, 9.10 for Ubuntu, etc.). This causes a variety of issues, including PDF normalization failures.

**Describe the solution you'd like to see implemented.**
Upgrade to the most recent version available for each environment.

**Describe alternatives you've considered.**
None, we really just need to upgrade this.

**Additional context**
This issue was [previously filed](https://github.com/artefactual/archivematica/issues/725) but we ended up addressing the stated issue in a different way. 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment] 2019-05-13 17:22
@ablwr could you please investigate/size?

**Comment by ablwr** [comment] 2019-06-19 15:25
Ubuntu 16.04 and 18.04 are already up to version 9.26! That's only one behind the most recent release.

So the only thing that needs to change is manually updated CentOS to a higher version (CentOS is still on 9.07). Preferably 9.26 as well, so they are all on the same and there are no surprises.

Since an upgrade has been done for a client and it was successful, that's some confidence in that the upgrade will be easy for CentOS. I think we should go ahead and update the installation scripts for our CentOS machines.

Here's the [commit](https://github.com/artefactual-labs/am-packbuild/commit/954e49b459fa663cd6423ed584bf62cae1780ec6) from when @scollazo made a package for a Ghostscript 9.20 -- I think a relatively minor modification of this would get us up to 9.26 for the next release.

**Comment by sromkey** [comment] 2019-06-19 15:51
hot potato- assigning to @joel-simpson for dev assignment!!

**Comment by scollazo** [comment] 2019-06-25 23:41
9.26 is being more complex than expected, mostly due to changes made for 9.22 release[, that split the package in multiple subpackages](https://src.fedoraproject.org/rpms/ghostscript/c/fe7ddccb2635e55c391b3f1a7982a5dcc5684a37) that we also need to build in order to make it work on centos

**Comment by ablwr** [comment] 2019-06-26 17:18
Ahhhhhh... thanks @scollazo. Were you saying 9.20 is the best for the update? 

It'd be great to strive for consistency across deployments, but I think going up to 9.20 is going to bring in most of the feature updates, yeah. I think it's better to do that now rather than do the more difficult task down the road.

**Comment by scollazo** [comment] 2019-06-28 10:29
Ghostscript 9.20 built and uploaded to https://packages.archivematica.org/1.10.x/centos-extras/

**Closed** 2019-07-09 15:57 UTC
Labels: Status: review, Type: enhancement

**Comment by titansmc** [comment] 2019-09-19 10:04
Hi,
I am installing archivematica 1.10 and I have conflicts when installing

archivematica-mcp-client

```

Transaction check error:
  file /usr/bin/ghostscript conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/bin/gs conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/bin/ps2ascii conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/bin/ps2epsi conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/lib64/libgs.so.9 conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and libgs-9.25-2.el7_7.2.x86_64
  file /usr/lib64/libijs-0.35.so conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and libgs-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/dvipdf.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/ghostscript.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/gs.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/gslp.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/gsnd.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/pdf2dsc.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/pdf2ps.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/pf2afm.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/pfbtopfa.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/printafm.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/ps2ascii.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/ps2epsi.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/ps2pdf.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/ps2pdfwr.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
  file /usr/share/man/man1/ps2ps.1.gz conflicts between attempted installs of ghostscript-core-9.20-12.el7.x86_64 and ghostscript-9.25-2.el7_7.2.x86_64
```
How can this be fixed? It is running CentOS 7.6.

Cheers.

**Comment by sromkey** [comment] 2019-09-23 15:18
@titansmc since this might be specific to your setup rather than a reason to re-open the issue, could you post to our user forum instead? https://groups.google.com/forum/#!forum/archivematica 

We didn't experience this in any of our testing.

**Comment by titansmc** [comment] 2019-09-23 15:33
Hi,
Thanks. Someone else was able to reproduce it [915](https://github.com/archivematica/Issues/issues/915)
