### ISSUE TITLE
Internal server error. Sorry! Something wrong happened. Please, contact with your administrator.

### ISSUE THREAD

**Issue by titansmc** [archivematica/Issues#1003] opened 2019-11-22 15:19 UTC
**Expected behaviour**
Login without any problem

**Current behaviour**
Shows 
`Internal server error. Sorry! Something wrong happened. Please, contact with your administrator.`
**Steps to reproduce**
Don't know, I just tried to log in after installing it 2 months ago and now I cannot anymore. I see:
```
DEBUG     2019-11-22 15:15:41  archivematica.dashboard:models:create_user_agent:78:  Caught post_save signal from <class 'django.contrib.auth.models.User'> with instance <User: admin>
ERROR     2019-11-22 15:15:41  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /administration/accounts/login/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/contrib/auth/views.py", line 51, in login
    auth_login(request, form.get_user())
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 117, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/contrib/auth/models.py", line 26, in update_last_login
    user.save(update_fields=['last_login'])
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/share/archivematica/dashboard/main/models.py", line 85, in create_user_agent
    u=instance
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 4: ordinal not in range(128)
```
What I did is tried to change the password through CLI and it seems that the pasword changed got applied even though I was receiving the same error. Now I have logged in with a password that only has numbers and letters but still get the same error.

**Your environment (version of Archivematica, operating system, other relevant details)**
latest

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by replaceafill** [comment] 2019-11-22 17:47
Hello @titansmc! I think you're experiencing https://github.com/archivematica/Issues/issues/261 Your user probably has non-ascii characters in the first name or last name fields which is currently not possible until that issue is fixed.

Closing this as duplicate of https://github.com/archivematica/Issues/issues/261 .

**Closed by replaceafill** 2019-11-22 17:47 UTC
