### ISSUE TITLE
Problem: partial AIP reingest fails at microservice: Process submission documentation

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1060] opened 2020-01-15 01:16 UTC
**Expected behaviour**
A partially reingested AIP should make it through to store AIP

**Current behaviour**
The AIP is failing at job: Assign checksums and filesizes to submissionDocumentation and job: Scan for viruses in submissionDocumentation:

`Errors and diagnostics (stderr)
updatesizeandchecksum_v0.0: INFO      2020-01-15 01:05:16,877  archivematica.mcp.client.updateSizeAndChecksum.call:171  Invoked as updatesizeandchecksum_v0.0 /var/archivematica/sharedDirectory/ --filePath /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/another_test-efc3678c-9925-4146-aefe-1b7bccf6a9df/objects/submissionDocumentation/transfer-another_test-d1d4d66c-f63e-4388-a66c-03eff2080dec/METS.xml --fileUUID db07db31-d96b-4346-8f78-cb41da026c8a --eventIdentifierUUID 43d54fc7-98cc-4d6a-89ec-ed173bb35324 --date 2020-01-15T01:05:16.869981+00:00.
[Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/another_test-efc3678c-9925-4146-aefe-1b7bccf6a9df/objects/submissionDocumentation/transfer-another_test-d1d4d66c-f63e-4388-a66c-03eff2080dec/METS.xml'Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/job.py", line 111, in JobContext
    yield
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/update_size_and_checksum.py", line 182, in call
    args.event_uuid,
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/update_size_and_checksum.py", line 146, in main
    updateSizeAndChecksum(file_uuid, file_path, date, event_uuid, **kw)
  File "/usr/lib/archivematica/archivematicaCommon/fileOperations.py", line 61, in updateSizeAndChecksum
    fileSize = os.path.getsize(filePath)
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/another_test-efc3678c-9925-4146-aefe-1b7bccf6a9df/objects/submissionDocumentation/transfer-another_test-d1d4d66c-f63e-4388-a66c-03eff2080dec/METS.xml'`

`Errors and diagnostics (stderr)
archivematicaclamscan_v0.0: INFO      2020-01-15 01:05:17,662  archivematica.mcp.client.clamscan.scan_file:347  Using scanner ClamAV (clamd) (ClamAV 0.102.1 - 25695/Tue Jan 14 13:34:00 2020)
archivematicaclamscan_v0.0: INFO      2020-01-15 01:05:17,662  archivematica.mcp.client.clamscan.pass_by_stream:184  File contents being streamed to Clamdscan.
archivematicaclamscan_v0.0: ERROR     2020-01-15 01:05:17,662  archivematica.mcp.client.clamscan.clamd_exception_handler:160  Virus scanning failed: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/another_test-efc3678c-9925-4146-aefe-1b7bccf6a9df/objects/submissionDocumentation/transfer-another_test-d1d4d66c-f63e-4388-a66c-03eff2080dec/METS.xml'
Traceback (most recent call last):
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/archivematica_clamscan.py", line 124, in scan
    result = getattr(self, method_name)(path)
  File "/opt/archivematica/archivematica/src/MCPClient/lib/clientScripts/archivematica_clamscan.py", line 185, in pass_by_stream
    return self.client.instream(open(path))
IOError: [Errno 2] No such file or directory: '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/another_test-efc3678c-9925-4146-aefe-1b7bccf6a9df/objects/submissionDocumentation/transfer-another_test-d1d4d66c-f63e-4388-a66c-03eff2080dec/METS.xml'
archivematicaclamscan_v0.0: INFO      2020-01-15 01:05:17,662  archivematica.mcp.client.clamscan.scan_file:361  File /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/another_test-efc3678c-9925-4146-aefe-1b7bccf6a9df/objects/submissionDocumentation/transfer-another_test-d1d4d66c-f63e-4388-a66c-03eff2080dec/METS.xml scanned!
archivematicaclamscan_v0.0: INFO      2020-01-15 01:05:17,662  archivematica.mcp.client.clamscan.queue_event:243  Recording new event for file db07db31-d96b-4346-8f78-cb41da026c8a (outcome: Fail)`

**Steps to reproduce**
Create an AIP and place it in Archival storage. Partially reingest the AIP.

**Your environment (version of Archivematica, operating system, other relevant details)**
AM 1.11-qa (bionic and xenial). Tested with sampledata/Images

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by ross-spencer** [comment] 2020-01-15 15:41
cc. @sromkey @evelynPM I believe this is a duplicate of https://github.com/archivematica/Issues/issues/955 and will be resolved as part of that fix which is currently just in CR.

**Comment by ross-spencer** [comment] 2020-01-22 16:33
This should now be resolved via https://github.com/artefactual/archivematica/pull/1535/commits/7cf4550b1b5d921c39d02c7ddcbe135d1cc27627

@evelynPM once we get the test servers updated to reflect today's commits I'd love to get your feedback on this to make sure it is indeed resolved.

**Comment by sallain** [comment] 2020-03-23 23:41
This is working. Tested with qa/1.x on RPM and Bionic.

**Closed by sallain** 2020-03-23 23:41 UTC
Labels: Status: review, Type: regression
