### ISSUE TITLE
Problem: Partial (and Full) reingest removes mets:sourceMD from METS file

### ISSUE THREAD

**Issue by corinnemrogers** [archivematica/Issues#914] opened 2019-09-19 20:44 UTC
**Expected behaviour**
If mets:sourceMD and transfer_metadata are present in an AIP METS file, they should not be removed from the METS file during partial reingest of that AIP .

**Current behaviour**
mets:sourceMD is removed from METS file during partial reingest

**Steps to reproduce**
Download the METS file of an AIP; do a partial reingest of that AIP and compare the updated METS file to the original

**Your environment (version of Archivematica, OS version, etc)**
1.10

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by evelynPM** [comment] 2019-09-24 16:29
Note that sourceMD is not a standard section in all AIP METS files. It only appears when the AIP resulted from a bag transfer or from a forensic disk transfer for which the user entered metadata about the disk in the transfer tab.

**Comment by ross-spencer** [comment] 2019-09-25 09:48
This issue is partially related to https://github.com/archivematica/Issues/issues/636

It turns out (at the moment) reading our `mets` using `metsrw` (mets-reader-writer) the process is in-fact lossy. 

You can take a mets file with a sourceMD entry, and run it through this script here:
```python
import metsrw
mets = metsrw.METSDocument.fromfile("mets_with_source_md.xml")
print mets.tostring()
```
And an example result is shown [here](https://gist.github.com/ross-spencer/5726f4b3e9cb2ab8c1e0ac30b826b83a/revisions).

![image](https://user-images.githubusercontent.com/1880412/65589829-0098b700-df8a-11e9-82a5-d0387df40329.png)

I need to look at `metsrw` so understand what a fix looks like.

**Comment by ross-spencer** [comment] 2019-09-26 15:48
I believe the root cause of this is that `metsrw` does not seem to know that an `amdSec` can be associated with anything other than a file. it is trying to read the amdsecs associated with a `filesec`, but none other. The code where we begin to consume `amdsecs` is [here](https://github.com/artefactual-labs/mets-reader-writer/blob/58c429289e11c21c2e95f32b11eac9508c39e849/metsrw/mets.py#L369-L383). 

I started to look at a potential fix today but it will take time and I will make a note in Slack about that. 

I would like to propose:

1. We add this ability to `metsrw` to consume `amdsecs` from the structmap. 
2. Write tests to make sure that happens.
3. We'll then need to release `metsrw` or work with a commit in the Archivematica `requirements.txt.
4. Automated tests for reingest, to purposely check for the `scopeMD` for a bag transfer would also be good to round off this work. Potentially other unit tests in `create_mets_aip_v2.py`.

It's a chunk of work.

**Comment by jraddaoui** [comment] 2019-10-07 18:08
Fix merged in latest qa and stable branches from AM and the SS.

**Comment by sromkey** [comment] 2019-10-10 15:40
I tested this by storing an AIP from a bag transfer and then reingesting that AIP- the sourceMD was present in the METS file both before and after reingest.

Marking as done.

**Closed** 2019-10-10 15:40 UTC
Labels: Severity: high, Status: review, Type: bug
