### ISSUE TITLE
Problem: remove all SIPs from Ingest tab fails on SIPs for which last decision point involved a DIP

### ISSUE THREAD

**Issue by evelynPM** [archivematica/Issues#1303] opened 2020-09-02 22:15 UTC
**Expected behaviour**
Clicking on the Remove all button at the top of the page in the Ingest tab removes all completed SIPs from the dashboard

**Current behaviour**
SIPs that had DIPs aren't removed from the dashboard

**Steps to reproduce**
Start a transfer
At normalize, select Normalize for access
Upload and/or store the DIP
Store the AIP
Click on the Remove all button

**Your environment (version of Archivematica, operating system, other relevant details)**
QA-1.12 on bionic

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sallain** [comment] 2020-09-02 22:19
This also seems to be the case on 1.11.

**Comment by replaceafill** [comment] 2020-09-02 22:24
Is this a duplicate of https://github.com/archivematica/Issues/issues/865?

**Comment by sallain** [comment] 2020-09-02 22:29
Excellent catch @replaceafill! We can close this issue in favour of that one since #865 has more detail.

**Closed by sallain** 2020-09-02 22:29 UTC
Labels: Type: bug
