### ISSUE TITLE
Problem: S3 spaces don't allow DIP Storage locations

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [archivematica/Issues#1442] opened 2021-04-27 16:31 UTC
S3 Locations do not allow DIP Storage as a valid option. Will create pull request.

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by sromkey** [comment] 2021-04-28 15:38
Thank you for contributing! I've asked @sevein to take a look at your PR.

**Comment by sevein** [comment] 2021-05-04 07:01
https://github.com/artefactual/archivematica-storage-service/pull/594 is merged, but I'll leave the issue "In progress" to remind us that we need to update the docs (https://github.com/artefactual/archivematica-storage-service-docs/blob/0.18/administrators.rst#s3-amazon; @fitnycdigitalinitiatives do you have time for this?) and possibly writing a new [integration test](https://github.com/artefactual/archivematica-storage-service/tree/qa/0.x/integration) since its environment has already MinIO set up.

**Comment by fitnycdigitalinitiatives** [comment] 2021-05-04 13:46
I just created a pull for the updated docs, but I'm a little unfamiliar with the integration test process. I imagine I could figure it out but more uncertain how soon I would be able to get to it.

**Comment by sevein** [comment] 2021-05-04 17:02
No worries, we can do that some other time.

**Comment by replaceafill** [comment] 2021-06-25 13:41
I confirmed this works:
* The `DIP Storage` option is now enabled in the `Create Location` form
![Captura de pantalla de 2021-06-25 07-32-22](https://user-images.githubusercontent.com/560781/123433457-b8585f80-d588-11eb-8be3-b2d55885309b.png)

* The DIP was uploaded to AWS S3 after the transfer was done
![Captura de pantalla de 2021-06-25 07-36-08](https://user-images.githubusercontent.com/560781/123433475-bdb5aa00-d588-11eb-8e05-c7f91ef6212e.png)

**Closed by replaceafill** 2021-06-25 13:41 UTC
Labels: Status: review, Type: enhancement
