### ISSUE TITLE
Problem: indexAip task fails when using a S3 aipstore

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#559] opened 2019-03-12 12:38 UTC
**Expected behaviour**
IndexAip step works without issues . This is a regression from Archivematica 1.8

**Current behaviour**
The indexAIP task fails with 
```
AIP does not exist at: < /path/to/aip.7z>
Error indexing AIP and AIP files
```

**Steps to reproduce**
Configure a S3 AipStore in the storage-service, and use it for storing the AIP

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.9 in Ubuntu Bionic

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment] 2019-03-12 12:45
Chatted with Santi to confirm I am seeing the same issues in my qa environment with settings that previously worked in 1.8, but can revert back to a previous deployment to test if absolutely needed but would be better if we have a 18 test environment already deployed.

**Comment by scollazo** [comment] 2019-03-12 16:52
This is also happening when using DuraSpace as AIP store

**Comment by ross-spencer** [comment] 2019-03-18 15:16
The problem was introduced in AM `1.9.0` here: https://github.com/artefactual/archivematica/commit/da59178679954f3fc496da538901234f987e99d4#diff-9b4f46e2e48ac68f1f5603497ac35736 where we used to use the staging path of the AIP to then retrieve statistics about it, we're now looking at the information from the storage service about it. Doing this means we don't need to check the path exists, subsequently failing if that path is already at a remote location. We can resolve this by simply passing the statistics through the function where possible, and not relying on paths having to exist.

**Comment by ross-spencer** [comment] 2019-03-18 18:27
Merged into `stable/1.9.x`.
TODO: cherry-pick into `qa/1.x`

**Comment by mamedin** [comment] 2019-03-19 17:02
I could reproduce the issue when the Storage Service is desployed in a separate VM (using AM v1.9.0). This the error when indexing the AIP:

<pre>
Mar 19 08:13:00 am1-new python[13483]: =============== STDOUT ===============
Mar 19 08:13:00 am1-new python[13483]: AIP info: [{u'status': u'UPLOADED', u'package_type': u'AIP', u'origin_pipeline': u'/api/v2/pipeline/13734857-ba7e-4105-9e0d-351d31620ef0/', u'uuid': u'e5323707-ff52-4dcd-9e
bd-6266d654467d', u'replicas': [], u'encrypted': False, u'current_path': u'e532/3707/ff52/4dcd/9ebd/6266/d654/467d/mamedin-pictures4-e5323707-ff52-4dcd-9ebd-6266d654467d.tar.bz2', u'replicated_package': None, u'
misc_attributes': {}, u'current_full_path': u'/amstorage/am1/aips/e532/3707/ff52/4dcd/9ebd/6266/d654/467d/mamedin-pictures4-e5323707-ff52-4dcd-9ebd-6266d654467d.tar.bz2', u'current_location': u'/api/v2/location/
b64c4ee2-3e80-48cf-8bc0-e7f24587ae16/', u'related_packages': [u'/api/v2/file/b684936b-4427-4ae9-8ce4-2e89c6509c8e/'], u'size': 21818247, u'resource_uri': u'/api/v2/file/e5323707-ff52-4dcd-9ebd-6266d654467d/'}]
Mar 19 08:13:00 am1-new python[13483]: Indexing additional identifiers %s []
Mar 19 08:13:00 am1-new python[13483]: Indexing AIP and AIP files
Mar 19 08:13:00 am1-new python[13483]: =============== END STDOUT ===============
Mar 19 08:13:00 am1-new python[13483]: =============== STDERR ===============
Mar 19 08:13:00 am1-new python[13483]: AIP does not exist at: /amstorage/am1/aips/e532/3707/ff52/4dcd/9ebd/6266/d654/467d/mamedin-pictures4-e5323707-ff52-4dcd-9ebd-6266d654467d.tar.bz2
Mar 19 08:13:00 am1-new python[13483]: Error indexing AIP and AIP files
Mar 19 08:13:00 am1-new python[13483]: =============== END STDERR ===============
</pre>

I tested https://github.com/artefactual/archivematica/pull/1369 with latest stable/1.9.x and it fixes the issue.

**Comment by sromkey** [comment] 2019-04-03 17:34
@mamedin tested this and it's working now.

**Comment by sallain** [comment] 2019-04-11 16:46
Added to release notes

**Closed** 2019-04-11 16:57 UTC
Labels: Severity: high, Status: verified, Type: regression
