### ISSUE TITLE
Problem: EICAR sample data is implemented incorrectly

### ISSUE THREAD

**Issue by sarah-mason** [archivematica/Issues#1137] opened 2020-03-05 16:36 UTC
**Expected behaviour**
According to the `README.md` you should get the following output from clamAV when running the following command in the CLI:

```
cmd: clamscan --max-filesize 32M *

 test.zero.byte.no-virus Empty file
 test.1M.eicar.with-virus: Eicar-Test-Signature FOUND
 test.1M.nukem.with-virus: Win.Trojan.Nukem-1 FOUND
 test.1M.null.no-virus: OK
 test.30M.eicar.with-virus: Eicar-Test-Signature FOUND
 test.30M.nukem.with-virus: Win.Trojan.Nukem-1 FOUND
 test.30M.null.no-virus: OK
 test.zip.eicar.with-virus.zip: Eicar-Test-Signature FOUND
```

**Current behaviour**
```
cmd: clamscan --max-filesize 32M *
README.md: OK
metadata/checksum.md5: OK
test.1M.eicar.with-virus: OK
test.1M.nukem.with-virus: Win.Trojan.Nukem-1 FOUND
test.1M.null.no-virus: OK
test.30M.eicar.with-virus: OK
test.30M.nukem.with-virus: Win.Trojan.Nukem-1 FOUND
test.30M.null.no-virus: OK
test.zero.byte.no-virus: Empty file
test.zip.eicar.with-virus.zip: Win.Test.EICAR_HDB-1 FOUND
```

`test.1M.eicar.with-virus` and `test.30M.eicar.with-virus` now return OK with updated clamAV virus scanners. The test data and `README.md` file should be investigated and updated.

**Steps to reproduce**
In CLI navigate to _archivematica-sampledata/TestTransfers/virusTests_ and run the command `clamscan --max-filesize 32M *`

In the Dashboard start a transfer of _archivematica-sampledata/TestTransfers/virusTests_ -- the Virus Scan will fail but the logs for `test.1M.eicar.with-virus` and `test.30M.eicar.with-virus` will read: 

```
archivematicaclamscan_v0.0: INFO      2020-03-05 15:42:05,493  archivematica.mcp.client.clamscan.scan_file:361  File /var/archivematica/sharedDirectory/currentlyProcessing/4-1_virus-c9a09250-4638-4a9b-80f9-71fdbd36b190/objects/test.1M.eicar.with-virus scanned!
archivematicaclamscan_v0.0: INFO      2020-03-05 15:42:05,494  archivematica.mcp.client.clamscan.queue_event:243  Recording new event for file e605b759-f0e2-4576-afd8-d95c142993a2 (outcome: Pass)
```

```
archivematicaclamscan_v0.0: INFO      2020-03-05 15:42:24,130  archivematica.mcp.client.clamscan.scan_file:361  File /var/archivematica/sharedDirectory/currentlyProcessing/4-1_virus-c9a09250-4638-4a9b-80f9-71fdbd36b190/objects/test.30M.eicar.with-virus scanned!
archivematicaclamscan_v0.0: INFO      2020-03-05 15:42:24,131  archivematica.mcp.client.clamscan.queue_event:243  Recording new event for file 03fa42c6-a7cf-458d-b2eb-b2eaf0a5741d (outcome: Pass)
```

**Your environment (version of Archivematica, operating system, other relevant details)**
1.10.1 Ubuntu Bionic
qa 1.11 CentOS

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by mamedin** [comment] 2020-03-05 17:08
I tested with a new text file, adding the following string and it has been detected as virus:
```
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
```

See: https://en.wikipedia.org/wiki/EICAR_test_file

We should change the eicar sampledata test files.

**Comment by ross-spencer** [comment] 2020-03-09 17:51
Odd one. Can't confirm if this was a regression in ClamAV. Would need to look at the signature definitions. Though, the only extraneous bytes allowed by the eicar spec are zeros. 

![image](https://user-images.githubusercontent.com/1880412/76242278-d15ec500-620c-11ea-83d1-132a9c44dcb9.png)

But according to the intended use, then perhaps only 68 bytes of specific white space characters were allowed:

* http://2016.eicar.org/86-0-Intended-use.html

Via https://serverfault.com/a/1005665

**Comment by ross-spencer** [comment] 2020-03-18 12:20
Resolved by https://github.com/artefactual/archivematica-sampledata/pull/75

**Closed by ross-spencer** 2020-03-18 12:20 UTC
