### ISSUE TITLE
  Problem AIP Store Failure in AM18 RPM upgrades

### ISSUE THREAD

**Issue by rodyoukai** [archivematica/Issues#382] opened 2018-12-13 16:27 UTC
**Expected behaviour**

Store AIP y correct location

**Current behaviour**

Failure 

```
500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:8001/api/v2/async/14/Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/job.py", line 102, in JobContext
    yield
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 313, in call
    args.sip_uuid, args.sip_name, args.sip_type))
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 212, in store_aip
    related_package_uuid)
  File "/usr/lib/archivematica/MCPClient/clientScripts/store_aip.py", line 67, in _create_file
    agents=get_agents_from_db(uuid)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 350, in create_file
    ret = wait_for_async(response)
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 223, in wait_for_async
    poll_response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-mcp-client/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:8001/api/v2/async/14/

```

**Steps to reproduce**

Select Store AIP in any location

**Your environment (version of Archivematica, OS version, etc)**

CENTOS 7, Archivematica 1.8 upgrading for 1.7 

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by mamedin** [comment] 2018-12-14 08:50
Same error https://github.com/archivematica/Issues/issues/260

@rodyoukai,  Do you have an accented character in your PREMIS agent settings?

**Comment by sevein** [comment] 2018-12-14 17:48
@rodyoukai in addition to @mamedin's question, it'd be useful if you provide the log events emitted by Storage Service. Thank you!

**Comment by sevein** [comment] 2018-12-19 18:42
Duplicate of https://github.com/archivematica/Issues/issues/260

**Closed by sevein** 2018-12-19 18:42 UTC
