### ISSUE TITLE
Performance: watched directory monitoring is slower than it could be

### ISSUE THREAD

**Issue by cole** [archivematica/Issues#916] opened 2019-09-20 19:04 UTC
**Please describe the problem you'd like to be solved.**

MCPServer could be more efficient in how it observes watched directories for changes. Currently it checks on a timer, and compares directory contents to what it last saw. There are many places in a typical workflow where a transfer is moved to a watched directory, and picked up again from there, so using a timer necessarily delays transfer processing somewhat.

**Describe the solution you'd like to see implemented.**

[Inotify](http://man7.org/linux/man-pages/man7/inotify.7.html) is a Linux API for observing filesystem changes as an alternative to polling. Inotify only works on linux, and for local filesystems, so it would have to be opt in.

**Describe alternatives you've considered.**

We could leave watched directory observation as is.

**Additional context**

This work was originally done in https://github.com/artefactual/archivematica/pull/1472, but has been pulled out for easier code review.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Done:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment] 2019-09-21 12:52
Hi @cole is there an alternative to making this an additional configurable option for the MCP server? Can its use be determined by the storage space for example?

**Comment by cole** [comment] 2019-09-22 18:02
@ross-spencer I don't think we can tell from the storage space if NFS is being used. @sevein has suggested a command line check (`stat -f -L -c %T /var/archivematica/sharedDirectory`) — I was thinking an option is more explicit though. It seems like we should have users opt into this case since many are using NFS mounts.

**Comment by cole** [comment] 2019-09-22 18:07
I should clairify the performance gains likely here. Polling takes up to the configured interval (default 1 second) to observe watched directory activity. There seem to be ~13 places in the default automated transfer workflow (including SIP ingest) where a watched directory is used to start the next chain, resulting in a delay of 0-13 seconds per transfer. With inotify there is essentially no delay, so we should see savings of up to 0-13 seconds per transfer, no matter the total transfer time. Not much of an improvement for 2 hour transfers, but an easy gain for 2 minute transfers.

**Comment by cole** [comment] 2019-09-22 18:09
@joel-simpson @sromkey can we milestone this issue as well for the 1.11 performance improvements?

**Comment by sevein** [comment] 2020-03-12 22:08
We probably haven't done enough testing at scale using `ARCHIVEMATICA_MCPSERVER_MCPSERVER_WATCH_DIRECTORY_METHOD=inotify` introduced in https://github.com/artefactual/archivematica/pull/1484 but we know it works and it passes the tests. Also, the old watching mechanism (`poll`) is still available and remains the default option.

This issue relates somehow to #1111 because, as `inotify` being a faster mechanism to watch directories, we observed that a race condition that we were experiencing was happening more often.

**Comment by ross-spencer** [comment] 2020-03-25 15:34
Testing for 1.11, starting on Docker:
-----
Confirmed to work with these settings in Docker-compose:
```
  archivematica-mcp-server:
    build:
      context: "../src/archivematica/src"
      dockerfile: "MCPServer.Dockerfile"
    environment:
      DJANGO_SECRET_KEY: "12345"
      DJANGO_SETTINGS_MODULE: "settings.common"
      ARCHIVEMATICA_MCPSERVER_CLIENT_USER: "archivematica"
      ARCHIVEMATICA_MCPSERVER_CLIENT_PASSWORD: "demo"
      ARCHIVEMATICA_MCPSERVER_CLIENT_HOST: "mysql"
      ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE: "MCP"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_MCPARCHIVEMATICASERVER: "gearmand:4730"
      ARCHIVEMATICA_MCPSERVER_SEARCH_ENABLED: "${AM_SEARCH_ENABLED:-true}"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_PORT: "7999"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_ADDRESS: "0.0.0.0"
      ARCHIVEMATICA_MCPSERVER_MCPSERVER_WATCH_DIRECTORY_METHOD: "inotify" <-- inotify added here...
```
      
And then black-box With iNotify:

```
1 feature passed, 0 failed, 20 skipped
6 scenarios passed, 0 failed, 59 skipped
39 steps passed, 0 failed, 613 skipped, 0 undefined
Took 8m27.416s
```

```
1 feature passed, 0 failed, 20 skipped
6 scenarios passed, 0 failed, 59 skipped
39 steps passed, 0 failed, 613 skipped, 0 undefined
Took 6m13.980s
```

--

And for a timing comparison:

Without inotify:

```
1 feature passed, 0 failed, 20 skipped
6 scenarios passed, 0 failed, 59 skipped
39 steps passed, 0 failed, 613 skipped, 0 undefined
Took 7m3.089s
ross-spencer@a
```

```
1 feature passed, 0 failed, 20 skipped
6 scenarios passed, 0 failed, 59 skipped
39 steps passed, 0 failed, 613 skipped, 0 undefined
Took 6m25.344s
```
So for the few transfers in each black-box set, timing is about the same, but I can also see in the logs, `inotify` is being used and not used, e.g. for usage:
```
activity: DemoTransferCSV-7007af53-982c-4737-9877-c1d156a609fd
archivematica-mcp-server_1       | DEBUG    WatchDirs 2020-03-25 14:56:33 watch_dirs:watch_directories_inotify:110:  Watched dir /approveNormalization/ detected activity: DemoTransferCSV-7007af53-982c-4737-9877-c1d156a609fd
archivematica-mcp-server_1       | DEBUG    WatchDirs 2020-03-25 14:56:33 watch_dirs:watch_directories_inotify:110:  Watched dir /workFlowDecisions/metadataReminder/ detected activity: DemoTransferCSV-7007af53-982c-4737-9877-c1d156a609fd
archivematica-mcp-server_1       | DEBUG    WatchDirs 2020-03-25 14:57:00 watch_dirs:watch_directories_inotify:110:  Watched dir /workFlowDecisions/compressionAIPDecisions/ detected activity: DemoTransferCSV-7007af53-982c-4737-9877-c1d156a609fd
archivematica-mcp-server_1       | DEBUG    WatchDirs 2020-03-25 14:57:07 watch_dirs:watch_directories_inotify:110:  Watched dir /storeAIP/ detected activity: DemoTransferCSV-7007af53-982c-4737-9877-c1d156a609fd
```

**Comment by ross-spencer** [comment] 2020-03-25 17:25
Santi also stood up an Ubuntu and CentOS environment in Jenkins, modified the environment variable, and watched the tests pass. So it works which means inotify watched directories are there for folks wanting to take advantage of it in an NFS based environment somewhere down the line. I think we think this looks good for acceptance testing. 

Another one bites the dust! Closing... 

![image](https://media0.giphy.com/media/l3mZqe2SH1aiYSTdK/giphy.gif?cid=790b761125aa5bd21e029bb69db12f3fee4d09746d334cc9&rid=giphy.gif)

**Closed by ross-spencer** 2020-03-25 17:25 UTC
Labels: Piql NHA, Status: review, Type: enhancement
