### ISSUE TITLE
Problem: fileID fails after any fileID command is edited

### ISSUE THREAD

**Issue by kellyannewithane** [archivematica/Issues#485] opened 2019-02-05 22:07 UTC
**Expected behaviour**
When I choose Siegfried as the File ID tool, the tool should run.

**Current behaviour**
File ID fails when Siegfried is chosen - stderr shows the following output - `IDCommand with UUID 75290b14-2931-455f-bdde-3b4b3f8b7f15 does not exist.`

@peterVG was testing #213 in ambionic and changed the id command for fido and siegfried and then changed the commands back to original.

While testing #278 File ID failed.  Works if I choose Fido, does not work if I choose Siegfried.

**Steps to reproduce**
Run a test transfer, choose Siegfried as File ID tool.

**Your environment (version of Archivematica, OS version, etc)**
ambionic

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment] 2019-02-05 22:50
This is happening because the UUID of the command is hard-coded in the workflow data. Before JSON-encoded workflows were introduced, `fpr` was able to maintain the workflow data updated, e.g. the following entry was updated with the new `IDCommand` created in the FPR.

```json
{
    "description": {
        "en": "Identify using Siegfried"
    },
    "id": "25a91595-37f0-4373-a89a-56a757353fb8",
    "items": {
        "IDCommand": "75290b14-2931-455f-bdde-3b4b3f8b7f15"
    }
}
```

A few solutions off the top of my head:

1. Release AM19 with this issue listed as a known bug including some docs on how to update `workflow.json` manually. It may not be ideal since we haven't yet decided how workflows are going to be editable by users and updating a giant JSON document is not particularly easy.
2. Update `linkTaskManagerReplacementDicFromChoice` so the replacements can be populated dynamically for this particular case, e.g. include "Skip file identification" and look up the FPR to populate a list of other file identification commands. It'd be a temporary hack specific to file identification.
3. Similar to the above but using `linkTaskManagerGetMicroserviceGeneratedListInStdOut` - it may be trickier at this point to convert the chain links involved but doable.

For AM 1.10, we may want to revisit why file id is done this way compared to other FPR-based jobs. It's been explained to me before but I don't remember the details at the moment.

**Comment by ross-spencer** [comment] 2019-02-06 10:40
Hi @sevein cc. @sromkey one impact that comes to mind is what is the impact on upgrade? Will #devops need to record and then reconfigure the options that users have in place in the processing config for it to work as they expect if their defaults are different? (does that make sense?)

**Comment by sevein** [comment] 2019-02-06 18:43
@ross-spencer I'll investigate what's the result of a mismatch in the processing config. I don't know if it results on a user prompt or an error, but I'd rather have the former. I'll report back.

**Comment by sevein** [comment] 2019-02-07 23:39
I've confirmed that MCP prompts the user when the value in processing config is unknown. During upgrades, users will be prompted again unless they reconfigured the processing. In #1342, the new "No" response to "Do you want to perform file format identification?" links reuses the same UUID.

**Comment by sevein** [comment] 2019-02-07 23:41
I've submitted https://github.com/artefactual/archivematica/pull/1342 where the chain links involved are now converted into "Yes/No" questions. When "Yes" is used, we look up the preferred `fpr.IDCommand`. The model has been updated so we can have only one command enabled at a time.

**Comment by sallain** [comment] 2019-02-08 20:13
Editing the file ID command so that the PUID of the command is updated no longer causes file identification to fail with the error originally reported. I'd say this is fixed! Nice work, @sevein.

**Comment by scollazo** [comment] 2019-02-12 23:52
The changes to the processing configuration are breaking the automated tests:

<pre>
FAILED SUB-STEP: Given a base processing configuration for MediaConch tests
Substep info: Assertion Failed: FAILED SUB-STEP: Given that the user has ensured that the default processing config is in its default state
Substep info: Traceback (most recent call last):
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/env/lib/python3.5/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/env/lib/python3.5/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/steps.py", line 46, in step_impl
    context.am_user.browser.ensure_default_processing_config_in_default_state()
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/amuser/am_browser_ability.py", line 431, in ensure_default_processing_config_in_default_state
    choice_value='Use existing data')
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/amuser/am_browser_ability.py", line 377, in set_processing_config_decision
    decision_select.select_by_visible_text(choice_value)
  File "/home/jenkins/jenkins-home/workspace/deploy-pub/QA/Ubuntu-18.04-QA/env/lib/python3.5/site-packages/selenium/webdriver/support/select.py", line 140, in select_by_visible_text
    raise NoSuchElementException("Could not locate element with visible text: %s" % text)
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: Use existing data
</pre>

**Comment by replaceafill** [comment] 2019-02-13 14:49
@scollazo I've fixed most of the AMAUAT tests:

https://github.com/artefactual-labs/archivematica-acceptance-tests/commits/dev/issue-XXX-update-amauat-for-1.9

I plan to have that merged next week.

**Closed** 2019-03-06 19:59 UTC
Labels: Status: verified, Type: bug, Type: regression
