### ISSUE TITLE
Problem: AIP storage locations not correctly shown in "Job: Store AIP location" 

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#456] opened 2019-01-28 23:39 UTC
**Expected behaviour**
The dropdown list on Microservice: "Store AIP", Job: "Store AIP location" should show all enabled AIP Storage locations.

**Current behaviour**
The list of storage locations shown in the dropdown list is incorrect 

**Steps to reproduce**
1. Define several storage locations in the Storage Service, e.g.: 
![screen shot 2019-01-28 at 3 13 07 pm](https://user-images.githubusercontent.com/10160634/51873301-85570680-2311-11e9-8a51-3b7655c94f8a.png)

Checked that the AIP storage locations are also shown in the dashboard's Administration > AIP storage locations:
![screen shot 2019-01-28 at 3 13 30 pm](https://user-images.githubusercontent.com/10160634/51873383-c94a0b80-2311-11e9-8f42-7943029e5a5e.png)

2. Start an ingest

3. The dropdown box in Job: Store AIP location shows an incorrect list of locations (apart from the default location, none of the created locations is shown, also a "null" option is shown) 
![img_20190128_151646235](https://user-images.githubusercontent.com/10160634/51873446-0dd5a700-2312-11e9-988f-b5ad698c4e48.jpg)

**Your environment (version of Archivematica, OS version, etc)**
AM: qa/1.x commit 26bf5ec 
OS: ubuntu 16.04

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by ross-spencer** [comment] 2019-02-04 19:53
I can verify I see `null` on the referenced commit. In the latest commit https://github.com/artefactual/archivematica/commit/6689b64bd7323fafde64594afc9bfbd50fcff1ff I think perhaps the behavior has reverted to something more anticipated, where if you haven't specified a label for your storage location then you get a blank space. I will have a look at the the retrieve storage locations microservice and see if there's a reasonable looking fix. 

The workaround for readers of this ticket is to ensure that the storage location has a label, but I am also seeing a situation where not all my locations are returned even then so there seems to be a small issue retrieving this information from the Storage Service.

**Comment by ross-spencer** [comment] 2019-02-04 23:16
@hakamine @sromkey - there's an issue with the way we index the storage locations in the retrieve storage locations microservice:

`choices[storage_dir['description']] = storage_dir['resource_uri']`

See that we use `description` in the index field, we can leave that empty in the storage service or `None` as you see above, and here:

![image](https://user-images.githubusercontent.com/1880412/52243026-bc608580-28d8-11e9-98b8-202d29d971db.png)

And the API call returns:
```
        {
            "description": "", <--- blank
            "enabled": true,
            "path": "/var/archivematica/sharedDirectory/www/AIPsStore2",
            "pipeline": [
                "/api/v2/pipeline/e7c213e4-9cfa-4250-b45b-735b5a2e3827/"
            ],
            "purpose": "AS",
            "quota": null,
            "relative_path": "/var/archivematica/sharedDirectory/www/AIPsStore2",
            "resource_uri": "/api/v2/location/a4b00806-df88-4677-9a41-ae2bb423f1a4/",
            "space": "/api/v2/space/27648ea1-5545-4f77-bf2b-5e5541b8bd00/",
            "used": "0",
            "uuid": "a4b00806-df88-4677-9a41-ae2bb423f1a4"
        },
```

That will show up as a blank field in the user interface. 

Because `description` is an index we need it to be unique - but every time we reach an identical description, we overwrite a previous index value. So, @hakamine above didn't see three `null` values, just the one. In my storage service if i have three storage locations without a description i wont see three blank choices I'll see one.

In your test above, if `aipstore-test-es` is the last you configured, your blank (or null in the photo) will be pointing at that one.

For now, I'd like to propose:

1. we reverse the index to use a `uuid` and if there isn't a label/description, we can use the `uuid` in the interface, so the drop-down will show the UUID. 

2. If there is a description we can use that. 

3. If two locations have exactly the same description then one won't overwrite the other in the UI and the user will either need to change the labeling, or we can also show the `uuid` as well or instead. 

**Storage Service changes**

We can make the description a required field in the location form. I would have to ask @sevein, @jraddaoui or @replaceafill what they would anticipate the side-effects of that would be, if any, when users upgrade. I anticipate that the form would only complain if they try and edit it subsequently - but existing uses of it won't be impacted. 

---

I hope I've explained that okay, it's persnickety! (when isn't it?? :nerd_face:) How does that proposal to do each of those things, and add tests, sound?

**Comment by sevein** [comment] 2019-02-05 16:05
@ross-spencer you may also want to consider updating `linkTaskManagerGetUserChoiceFromMicroserviceGeneratedList` since `Store AIP location` is its only use case. E.g. the choices dict would be keyed by tuples (as long as they contain immutable values) if the manager is updated so it understands the new structure. On a side note, it'd be nice if the serialization method was using an interoperable format like JSON instead of Python literals. 

> We can make the description a required field in the location form. I would have to ask @sevein, @jraddaoui or @replaceafill what they would anticipate the side-effects of that would be, if any, when users upgrade. I anticipate that the form would only complain if they try and edit it subsequently - but existing uses of it won't be impacted.

You're probably right, `blank` is only about validation. But blank values have been allowed for so long that as a user I'd find annoying that this changes. It's not strictly necessary for us so we may prefer to leave it as it is.

**Comment by hakamine** [comment] 2019-02-05 18:42
Some additional info: IIRC in older versions of AM, when didn’t enter a description for the AIP location, the store AIP dropdown showed the path.

**Comment by jraddaoui** [comment] 2019-02-12 19:55
@ross-spencer fixes have been merged in qa/1.x. The "Store AIP location" and "Store DIP location" fields from the processing configuration forms should be tested too.

**Comment by sallain** [comment] 2019-02-12 20:51
Creating a new AIP or DIP storage location without a description results in the path being used as the location name in the processing configuration dropdowns, which I think is the criteria for marking this confirmed.

I created a few different scenarios to see about conflicts:

**Two spaces, same path, different descriptions**:
-- `/secondary`, "Secondary space"
-- `/secondary`, [null]

Result: two entries in the dropdown, "Secondary space" and `/secondary`. This is perhaps not ideal, but it's fine.

**Two spaces, same path, same description**:
-- `/secondary`, "Secondary space"
-- `/secondary`, "Secondary space"

Result: one entry in the dropdown. I think that's okay, because it's illogical to have identical entries appear as separate entries. In an ideal world, a storage service admin wouldn't be able to do this, but for now I don't think it will cause any problems.

**Two spaces, different paths, same description**:
-- `/secondary`, "Secondary space"
-- `/secondary-new`, "Secondary space"

Result: one entry in the dropdown ("Secondary space"). The logic doesn't look past the description to see if the two locations are different. If we wanted to fix it, the Storage Service could force uniqueness on the description, but I think it's a very very very unlikely edge case.

**Closed** 2019-03-06 19:59 UTC
Labels: Severity: high, Status: verified, Type: bug
