### ISSUE TITLE
Create METS script: allow loop to continue after exception

### ISSUE THREAD

**Issue by helenst** [archivematica/Issues#620] opened 2019-04-02 17:20 UTC
**Expected behaviour**
If a file without a UUID is found during METS creation, the error should be recorded and the script should be able to continue processing other files

**Current behaviour**
A file without a UUID causes the script to crash because after the error is detected, it attempts to continue operating on that file and use a variable it was unable to assign, resulting in an `UnboundLocalError`. This prevents the rest of the files from being processed.

**Steps to reproduce**
Would require arriving at this step having a file without a UUID - we encountered this during #613 as files without UUIDs were one of the symptoms. It should be possible to simulate this though.

**Your environment (version of Archivematica, OS version, etc)**
AM 1.9, Ubuntu 18.04 (using am compose environment)

(I have a PR to submit for this :)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sromkey** [comment] 2019-04-02 18:28
Hi @helenst - I'm a little concerned about the implications of letting processing continue if any file is missing its UUID- I'm of the opinion that this should be considered a critical error and processing shouldn't be allowed to continue. For what it's worth we are aware of #613 and it's likely to be addressed in the future although we're not in the position to put a milestone on it just yet. 
I'm interested in hearing if others have thoughts about the proposed approach to this problem!

**Comment by joel-simpson** [comment] 2019-04-02 18:52
if #613 is the cause of the problem, then it sounds like you'd end up with a situation where the files will all (eventually) have a UUID but some won't be recorded in the METs. That does feel like a critical error. 

Perhaps there is a way to skip the file temporarily, and then attempt to retry slightly later (or when all other files processed), at which point it should have a UUID?   (that sounds similar to what @helenst mentioned in #613 - if you introduce an artificial 5 second delay it appears to prevent errors from happening...  not sure if what I'm suggesting is more complex than simply finding a good solution for #613 ? ) 

Alternatively, it would be nice if the script failed gracefully instead of just crashing, so perhaps we could focus on that... i.e. figure out how to capture the error scenario and trigger the failed Ingest microservice. (and then fix 613 in some other way)

**Comment by ross-spencer** [comment] 2019-04-02 20:01
Hi everyone! I took a look at the PR and if it helps, the change will only ensure that the script completes and accurately records the number of errors found along the way, but won't actually allow an ingest to complete so I think it finds a nice balance.

The detail is the accumulator `error_count` which still gets updated just prior to the `continue`. That value is [returned at the end of the script](https://github.com/artefactual/archivematica/blob/023b3e39a4c9cd8498b278e547791582db240247/src/MCPClient/lib/clientScripts/create_mets_v2.py#L1813) meaning we can't return non-zero and so we fall back to the Failure microservice set of jobs.

It's a complex one! We've adopted a couple of patterns across client scripts, and this fits in quite nicely with the pattern implied by one of our more idiosyncratic ones.

**Comment by sromkey** [comment] 2019-04-02 20:02
Ah, that does help @ross-spencer ! Thanks for the clarification. In this case I think it should be considered for 1.10 so I'll add the triage label.

**Comment by helenst** [comment] 2019-04-03 08:22
Sorry for the confusion yes - the script will still fail as a whole and therefore still stop the ingest, but more nicely than crashing out of the loop :)

**Comment by sallain** [comment] 2019-07-08 20:12
@helenst FYI there is a RC for 1.10 if you want to test this out!

**Closed** 2019-07-08 20:13 UTC
Labels: Status: review
