### ISSUE TITLE
Problem: large transfers don't show up in Dashboard

### ISSUE THREAD

**Issue by peterVG** [archivematica/Issues#280] opened 2018-10-17 19:29 UTC
**Expected behaviour**
After "Start Transfer" is initiated on a large transfer (e.g. 1000+ files, 10+ MB each), the Transfer will appear on the Dashboard (to Approve Transfer) or to output results of the first "Verify transfer compliance" microservice (if "approve automatically") is selected. 

**Current behaviour**

The Archivematica Dashboard does not respond with any information after "Start Transfer" is initiated on a large transfer. The files in the transfer are all copied to `/var/archivematica/sharedDirectory/tmp/` but the task fails with a timeout error:

![screen shot 2018-10-17 at 12 22 31](https://user-images.githubusercontent.com/672121/47111093-6f608280-d207-11e8-886e-f011c1341f06.png)

**Steps to reproduce**

This is using a scalability testing collection currently mounted on AM 18.x Xenial containing 7500 files, 17 MB each, 124GB total. 

The following environment configurations are set:
`MCPServer_SS_Client_QUICK_Timeout: 120`
`MCPClient_SS_Client_QUICK_Timeout: 120`
`Dashboard_SS_Client_QUICK_Timeout: 120`

Start a transfer using: 

![screen shot 2018-10-17 at 12 28 03](https://user-images.githubusercontent.com/672121/47111349-2bba4880-d208-11e8-9514-8a1bb3ded41b.png)

**Your environment (version of Archivematica, OS version, etc)**

Archivematica 18x.qa (Xenial)

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment] 2018-10-26 02:04
I think I'm getting to the bottom of this... when a new transfer is started, AM asks SS to copy the contents from the transfer source location, the request is like the following:

```
curl -v \
        --request POST \
        --header "Content-Type: application/json" \
        --data @request.json \
        -H "Authorization: ApiKey test:test" \
                http://127.0.0.1:8000/api/v2/location/a2cb908c-6642-4083-b1f6-58e7851ffd6b/async/
```

Where `request.json` is:
```
{
  "files": [
    {
      "destination": "/var/archivematica/sharedDirectory/tmp/tmpx9pmPq/20181026012316/.",
      "source": "TestTransfers/acceptance-tests/performance/images-17M-each/."
    }
  ],
  "origin_location": "/api/v2/location/5cd81cba-3b13-4b37-8a96-84c1efcb0d2c/",
  "pipeline": "/api/v2/pipeline/91080bb9-6c56-46fd-a4b7-27d33484adbf/"
}
```

Storage Service receives the request, launches a thread to do the heavy work in the background and returns. When you run the command above, cURL recives the response but it hangs which I guess it means that the connection is not being closed by the server. This is similar to what we're seeing in the SS client that Archivematica implements.

```
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> POST /api/v2/location/a2cb908c-6642-4083-b1f6-58e7851ffd6b/async/ HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Authorization: ApiKey test:4525fd5272275caeac04a28447698c50
> Content-Length: 343
> 
* upload completely sent off: 343 out of 343 bytes
< HTTP/1.1 202 ACCEPTED
< Server: nginx
< Date: Fri, 26 Oct 2018 02:00:45 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept, Accept-Language, Cookie
< X-Frame-Options: SAMEORIGIN
< Location: http://127.0.0.1:8000/api/v2/async/57/
< Content-Language: en
< 
[hangs]
```

To consider, Nginx listens on `127.0.0.1:8000` and proxies the traffic to Gunicorn which is listening on `127.0.0.1:8001`. If I hit Gunicorn directly with cURL, the problem is not reproducible.

Also, if I update the SS code so the background thread is never started, the problem also disappears.

We shouldn't be launching threads? Nginx needs some tweaking? Investigating...

**Comment by sevein** [comment] 2018-10-26 02:19
Only reproducible with `worker_class=gevent`, not a problem when the class is `sync`.

**Comment by sevein** [comment] 2018-10-26 16:53
Another thought: SS's new async manager was included in the v0.12 release but we haven't hit this problem until now - very strange! Also, I can't reproduce locally when using the proxy.

**Comment by sevein** [comment] 2018-10-29 23:52
The environment where this issue was happening was rebuilt and the issue can't be reproduced again!
We will keep testing!

**Comment by sevein** [comment] 2018-10-30 17:52
This is ready for QA, @peterVG!

**Closed** 2018-11-22 16:05 UTC
Labels: Severity: high, Status: verified, Type: bug
