### ISSUE TITLE
Problem: Fixity API endpoint and fixity tool fails to check replicated uncompressed aips

### ISSUE THREAD

**Issue by scollazo** [archivematica/Issues#1054] opened 2020-01-14 15:50 UTC
**Expected behaviour**
When fixity is run, the aips stored in a "Replicator" AIP store are checked.

**Current behaviour**
Fixity fails to check replicated aips with
```
Storage service at "http://XX.XX.XX.XX:8000/" encountered an internal error while scanning AIP d6f6a9cc-8a9d-449e-8a0a-f4ab412a6717
```

The storage service log shows the following:
```
ERROR     2020-01-14 07:39:03  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/file/d6f6a9cc-8a9d-449e-8a0a-f4ab412a6717/check_fixity/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 135, in wrapper
    result = func(resource, request, bundle, **kwargs)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1366, in check_fixity_request
    force_local=force_local
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1927, in get_fixity_check_report_send_signals
    force_local=force_local
  File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1890, in check_fixity
    bag = bagit.Bag(path)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/bagit.py", line 305, in __init__
    self._open()
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/lib/python2.7/site-packages/bagit.py", line 330, in _open
    raise BagError(_("Expected bagit.txt does not exist: %s") % bagit_file_path)
BagError: Expected bagit.txt does not exist: /replica/d6f6/a9cc/8a9d/449e/8a0a/f4ab/412a/6717/replica-d6f6a9cc-8a9d-449e-8a0a-f4ab412a6717/bagit.txt
```

**Steps to reproduce**

- Configure a replicator space for an AIPstore
- Run a transfer
- Run ```fixity scanall```

**Your environment (version of Archivematica, operating system, other relevant details)**

AM qa/1.x on Centos 7, storing uncompressed AIPs

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by scollazo** [comment] 2020-01-14 15:52
Seems like the replicated bagit is in a folder inside the one the ss looks for:
```
BagError: Expected bagit.txt does not exist: /replica/d6f6/a9cc/8a9d/449e/8a0a/f4ab/412a/6717/replica-d6f6a9cc-8a9d-449e-8a0a-f4ab412a6717/bagit.txt
```
While the bagit.txt is in 
```
/replica/d6f6/a9cc/8a9d/449e/8a0a/f4ab/412a/6717/replica-d6f6a9cc-8a9d-449e-8a0a-f4ab412a6717/replica-88382ca3-ce2c-47cd-bfe2-95a739e2f83d/bagit.txt
```

**Comment by ross-spencer** [comment] 2020-01-15 14:45
Something like this going wrong with Fixity is often indicative of something going wrong with the fixity endpoint in the Storage Service, and indeed, that is what we're seeing here, and can be replicated.

1. It impacts Uncompressed AIPs, and doesn't seem to impact those that are zipped. 
2. The trace below shows what I'm seeing:

```
http -v --pretty=format \
>     GET "http://127.0.0.1:62081/api/v2/file/98667415-6ac6-489b-b192-779c3cc1150f/check_fixity/" \
>     Authorization:"ApiKey test:test" 
```

```
GET /api/v2/file/98667415-6ac6-489b-b192-779c3cc1150f/check_fixity/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: ApiKey test:test
Connection: keep-alive
Host: 127.0.0.1:62081
User-Agent: HTTPie/1.0.3



HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Wed, 15 Jan 2020 13:55:19 GMT
Server: nginx/1.16.1
Transfer-Encoding: chunked
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN

{
    "error_message": "Expected bagit.txt does not exist: /var/archivematica/sharedDirectory/SIPbackups/9866/7415/6ac6/489b/b192/779c/3cc1/150f/10a-98667415-6ac6-489b-b192-779c3cc1150f/bagit.txt",
    "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/site-packages/tastypie/resources.py\", line 220, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/src/storage_service/locations/api/resources.py\", line 135, in wrapper\n    result = func(resource, request, bundle, **kwargs)\n\n  File \"/src/storage_service/locations/api/resources.py\", line 1366, in check_fixity_request\n    force_local=force_local\n\n  File \"/src/storage_service/locations/models/package.py\", line 1930, in get_fixity_check_report_send_signals\n    force_local=force_local\n\n  File \"/src/storage_service/locations/models/package.py\", line 1893, in check_fixity\n    bag = bagit.Bag(path)\n\n  File \"/usr/local/bin/bagit.py\", line 305, in __init__\n    self._open()\n\n  File \"/usr/local/bin/bagit.py\", line 330, in _open\n    raise BagError(_(\"Expected bagit.txt does not exist: %s\") % bagit_file_path)\n\nBagError: Expected bagit.txt does not exist: /var/archivematica/sharedDirectory/SIPbackups/9866/7415/6ac6/489b/b192/779c/3cc1/150f/10a-98667415-6ac6-489b-b192-779c3cc1150f/bagit.txt\n"
}
```

It looks like there is a copy mistake in the replication process where the AIP is being copied including its top-level directory, into a replication AIP structure. This means that the bagit.txt is at the wrong level of the structure to be found.

The correct structure for an uncompressed AIP is:
```
AIP-folder -->
   bagi.txt
```

vs. the incorrect replicated structure: 
```
Repl-AIP-folder -->
   AIP-filder -->
      bagit.txt
``` 

If my AIP is `a9d2726c-51a9-4361-bd6e-1e0f8eeb0435` and my replication is `98667415-6ac6-489b-b192-779c3cc1150f` we can see `bagit.txt` clearly exists in the replica:

```
root@9b6fc8afd655:/var/archivematica/sharedDirectory/SIPbackups# tree 9866/
9866/
└── 7415
    └── 6ac6
        └── 489b
            └── b192
                └── 779c
                    └── 3cc1
                        └── 150f
                            └── 10a-98667415-6ac6-489b-b192-779c3cc1150f
                                └── 10a-a9d2726c-51a9-4361-bd6e-1e0f8eeb0435
                                    ├── bag-info.txt
                                    ├── bagit.txt
                                    ├── data
                                    │   ├── logs
                                    │   │   ├── fileFormatIdentification.log
                                    │   │   ├── filenameCleanup.log
                                    │   │   └── transfers
                                    │   │       └── 10a-388a7a42-bef7-4da5-b8d0-79d1966631b0
                                    │   │           └── logs
                                    │   │               ├── fileFormatIdentification.log
                                    │   │               └── filenameCleanup.log
                                    │   ├── METS.a9d2726c-51a9-4361-bd6e-1e0f8eeb0435.xml
                                    │   ├── objects
                                    │   │   ├── Cv7a7v7WAAADJTO.jpg
                                    │   │   ├── metadata
                                    │   │   │   └── transfers
                                    │   │   │       └── 10a-388a7a42-bef7-4da5-b8d0-79d1966631b0
                                    │   │   │           └── directory_tree.txt
                                    │   │   └── submissionDocumentation
                                    │   │       └── transfer-10a-388a7a42-bef7-4da5-b8d0-79d1966631b0
                                    │   │           └── METS.xml
                                    │   └── README.html
                                    ├── manifest-sha256.txt
                                    └── tagmanifest-sha256.txt

20 directories, 13 files
```

But you can compare the AIP directories:
```
root@9b6fc8afd655:/var/archivematica/sharedDirectory/www/AIPsStore# tree -d a9d2/
a9d2/
└── 726c
    └── 51a9
        └── 4361
            └── bd6e
                └── 1e0f
                    └── 8eeb
                        └── 0435
                            └── 10a-a9d2726c-51a9-4361-bd6e-1e0f8eeb0435
                                └── data
                                    ├── logs
                                    │   └── transfers
                                    │       └── 10a-388a7a42-bef7-4da5-b8d0-79d1966631b0
                                    │           └── logs
                                    └── objects
                                        ├── metadata
                                        │   └── transfers
                                        │       └── 10a-388a7a42-bef7-4da5-b8d0-79d1966631b0
                                        └── submissionDocumentation
                                            └── transfer-10a-388a7a42-bef7-4da5-b8d0-79d1966631b0

19 directories
```
**NB.** Note there are 19.

And the replication:
```
root@9b6fc8afd655:/var/archivematica/sharedDirectory/SIPbackups# tree 9866/ -d
9866/
└── 7415
    └── 6ac6
        └── 489b
            └── b192
                └── 779c
                    └── 3cc1
                        └── 150f
                            └── 10a-98667415-6ac6-489b-b192-779c3cc1150f      <--- Shouldn't be here
                                └── 10a-a9d2726c-51a9-4361-bd6e-1e0f8eeb0435
                                    └── data
                                        ├── logs
                                        │   └── transfers
                                        │       └── 10a-388a7a42-bef7-4da5-b8d0-79d1966631b0
                                        │           └── logs
                                        └── objects
                                            ├── metadata
                                            │   └── transfers
                                            │       └── 10a-388a7a42-bef7-4da5-b8d0-79d1966631b0
                                            └── submissionDocumentation
                                                └── transfer-10a-388a7a42-bef7-4da5-b8d0-79d1966631b0

20 directories
```
**NB.** 20 directories when there should only be 19.

```
    └── 150f
        └── 10a-98667415-6ac6-489b-b192-779c3cc1150f      <--- Shouldn't be here
            └── 10a-a9d2726c-51a9-4361-bd6e-1e0f8eeb0435
                └── data
```
When you download the `tar` of the AIP you can see this second directory too. 

A brief test on `1.10.1` shows that this isn't a regression.

I will amend the title to reflex the impact on the API endpoint used in this instance.

**Comment by scollazo** [comment] 2020-01-29 15:25
After meeting with NHA, we might need to differentiate between online replicas (the ones that can be checked with fixity), and offline ones (mostly, tapes), where it doesn't make sense to use fixity.

**Comment by ross-spencer** [comment] 2020-01-30 13:30
Ah, that's an interesting request @scollazo I immediately thought that should be easy, the API docs however do not describe a mechanism to filter by location: [Get all packages](ttps://wiki.archivematica.org/Storage_Service_API#Get_all_packages). 

Currently the emphasis would be on the consumer of the endpoint, or AMClient output filtering by location for themselves. 

I have 8 packages in three locations (two spaces) at present. In this case two encrypted locations and one standard AIP store. The listing endpoint will list all:

```            
$ http --pretty=format  \
   GET "http://127.0.0.1:62081/api/v2/file/"  \
   Authorization:"ApiKey test:test" | grep current_path | sort | uniq
            "current_path": "1f40/b55c/f0d1/4e58/b578/f6d3/3d0b/6f0d/tar_test-1f40b55c-f0d1-4e58-b578-f6d33d0b6f0d",
            "current_path": "7aa7/249d/69dc/45e6/9046/ceff/bdc0/89a6/amauat-transfer_1580232651-7aa7249d-69dc-45e6-9046-ceffbdc089a6.7z",
            "current_path": "849e/5329/f9dc/49e8/a6e1/8d71/9c19/57a8/demo_transfer-849e5329-f9dc-49e8-a6e1-8d719c1957a8.7z",
            "current_path": "8ece/bd75/bbd9/4a9a/8821/e140/278d/cdad/encrypt_test-8ecebd75-bbd9-4a9a-8821-e140278dcdad.7z",
            "current_path": "ceea/9ebd/68cb/4ea8/843b/0e53/15f0/f1a0/amauat-transfer_1580232765-ceea9ebd-68cb-4ea8-843b-0e5315f0f1a0",
            "current_path": "d266/8952/8cb6/4d65/a356/066b/ca4f/4a18/amauat-transfer_1580232942-d2668952-8cb6-4d65-a356-066bca4f4a18.7z",
            "current_path": "ea2d/974a/8a6d/4824/8c2f/a806/54d1/0c1c/BagTransfer-ea2d974a-8a6d-4824-8c2f-a80654d10c1c.7z",
            "current_path": "originals/amauat-transfer_1580232852-188f7790-036c-40a5-b5d8-992500234990",
```

```
$ http --pretty=format  \
   GET "http://127.0.0.1:62081/api/v2/file/"  \
   Authorization:"ApiKey test:test" | grep current_path | sort | uniq | wc -l
8
```

```
$ http --pretty=format     GET "http://127.0.0.1:62081/api/v2/file/"  \
   Authorization:"ApiKey test:test" | grep current_location | sort | uniq
            "current_location": "/api/v2/location/0ab6e416-f1b9-4356-8b8b-8619888f32f6/",
            "current_location": "/api/v2/location/be25947c-dc85-4e5e-bed4-31ecfd1e6c68/",
            "current_location": "/api/v2/location/d8030e77-1082-42d2-b1e9-d6981ec01355/",
```           

So, depending on how that requirement evolves for the client and their willingness to do that post-processing of the endpoint data to pipe into `fixity` then it seems like logging a feature request might be a good idea as a first step to satisfying it where we'd want to filter locations to a) files not on tape, and b), where that location is a replicator. Then that would likely need to be built into the fixity app too.

**Comment by joel-simpson** [comment] 2020-02-18 20:49
Just to confirm - we discussed with NHA whether all replicated locations would be accessible / online and they indicated that they should be. So for now we've agreed to work on the defect noted in this issue (where this extra directory is being created).  
As @ross-spencer notes, a useful enhancement at some point would be to be able to filter on location or type of location etc, but for now we're going to assume that is not needed.

**Comment by ross-spencer** [comment] 2020-03-23 22:32
I can verify the endpoint in CentOS by doing the following using two existing replicated packages.

1. I have two packages, one is a replica of the other: `e545e67c-24e6-4f02-9c04-a167ab51bb9b` and `2abd43d3-8c47-4fb4-804e-80895358a120`:

![image](https://user-images.githubusercontent.com/1880412/77368437-98594100-6d32-11ea-9e64-e416362d8b5e.png)

I can then create a `check_fixity` URL as follows: `http://am111centos.qa.archivematica.net:8000/api/v2/file/<UUID>/check_fixity/`

Resulting in:

http://am111centos.qa.archivematica.net:8000/api/v2/file/e545e67c-24e6-4f02-9c04-a167ab51bb9b/check_fixity/

That and its counter-part should work

http://am111centos.qa.archivematica.net:8000/api/v2/file/2abd43d3-8c47-4fb4-804e-80895358a120/check_fixity/

For both we see:

![image](https://user-images.githubusercontent.com/1880412/77368587-ed955280-6d32-11ea-9858-124f9fcc13dc.png)

![image](https://user-images.githubusercontent.com/1880412/77368608-f7b75100-6d32-11ea-9cea-a70d1944f3ed.png)

**NB.** Screenshots provided to show full path.

Not moving this to closed as it looks like we will run the fixity app to confirm as well.

**Comment by ross-spencer** [comment] 2020-03-23 22:39
Word from @currmie on Slack https://github.com/archivematica/Issues/issues/1054 is :heavy_check_mark: as [Fixity](https://github.com/artefactual/fixity) was tested on Bionic last week including `3e6ad4fa-d543-4b08-a5ef-17757c70b9cb` and replicated package `e514446f-879a-4800-9c20-a6f52ef2513e`.

http://am111bionic.qa.archivematica.net:8000/api/v2/file/3e6ad4fa-d543-4b08-a5ef-17757c70b9cb/check_fixity/

http://am111bionic.qa.archivematica.net:8000/api/v2/file/e514446f-879a-4800-9c20-a6f52ef2513e/check_fixity/

**Closed by ross-spencer** 2020-03-23 22:39 UTC
Labels: API, Piql NHA, Status: in progress, Status: review, Type: bug

**Comment by ross-spencer** [comment] 2020-03-23 22:55
This ticket is being continued in https://github.com/archivematica/Issues/issues/1149 and has a potential fix https://github.com/artefactual/archivematica-storage-service/pull/524.

**Comment by amayita** [comment] 2020-05-06 17:26
I am seeing this issue in a Client where fixity consistently fails for the replicated AIP.
