### ISSUE TITLE
"Create SIP from transfer objects" fails when directories contain UUIDs

### ISSUE THREAD

**Issue by jlj5aj** [archivematica/Issues#192] opened 2018-09-21 15:46 UTC
**Expected behaviour**
The createSIPfromTransferObjects.py script should run successfully when directories contain UUIDs.

**Current behaviour**
The script crashes with the following error:

```
Standard error (stderr)

Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/createSIPfromTransferObjects.py", line 80, in <module>
    sip.diruuids = True
AttributeError: 'unicode' object has no attribute 'diruuids'
```

**Steps to reproduce**
Create a SIP from a transfer when "Assign UUIDs to directories" is set to Yes

Potential fix here: https://github.com/artefactual/archivematica/pull/1267

**Your environment (version of Archivematica, OS version, etc)**
Archivematica 1.7.1 on CentOS 7.5

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Release documentation (e.g. release notes, wiki documentation, etc) regarding this issue has been written 👍

**Comment by sromkey** [comment] 2018-09-21 16:10
Hi @jlj5aj , thanks for reporting! We're having trouble reproducing the error.  Did you directories have special characters in them, or anything else we should know about?

**Comment by jlj5aj** [comment] 2018-09-21 16:26
Hi @sromkey , I don't see any obvious special characters in the directory names.  To be sure, I just checked all directories underneath this transfer and they contain no characters outside of [0-9a-z_-].  Below is the complete set of info shown on the task page.  Please let me know if there is any further information I can provide, such as log files, database entries, etc.

```
Transfer 270c4c18-c501-4444-90ec-005d874547f5 > Create SIP from transfer objects > Tasks 

Task d30d5982-f035-47d0-be96-af0dbcb2d360

File UUID
    Unknown
File name
    20180906_ShepTest-270c4c18-c501-4444-90ec-005d874547f5
Client
    amatica.lib.virginia.edu_1
Exit code
    1 

Start time
    9/7/2018, 12:36:46 PM
End time
    9/7/2018, 12:36:47 PM
Created time
    9/7/2018, 12:36:46 PM
Duration
    1 seconds(s)
```
```
Module createSIPfromTransferObjects_v0.0

"/var/archivematica/sharedDirectory/currentlyProcessing/20180906_ShepTest-270c4c18-c501-4444-90ec-005d874547f5/objects/" "20180906_ShepTest" "270c4c18-c501-4444-90ec-005d874547f5" "/var/archivematica/sharedDirectory/currentlyProcessing/" "%sharedPath%watchedDirectories/system/autoProcessSIP/" "%sharedPath%"
```
```
Standard streams
```
```
Standard output (stdout)

sip_uuid None
sip_type SIP
```
```
Standard error (stderr)

Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/createSIPfromTransferObjects.py", line 80, in <module>
    sip.diruuids = True
AttributeError: 'unicode' object has no attribute 'diruuids'
```

**Comment by jlj5aj** [comment] 2018-09-21 16:32
I should add that applying the patch linked above allowed this step to succeed (I think this was a separate transfer, but with the same name and contents):
```
Standard output (stdout)

sip_uuid None
sip_type SIP
Creating SIP: 10bc9281-5759-4750-a2bb-26e0734e6279 - %sharedPath%watchedDirectories/system/autoProcessSIP/20180906_ShepTest/
```

**Comment by sromkey** [comment] 2018-09-21 16:33
thanks @jlj5aj ! Some of our developers have looked and agree that the code you fixed should have been breaking, we're now more puzzled about why we can't reproduce it! @jrwdunham I think you're most familiar with this, can you take a look?

**Comment by jrwdunham** [comment] 2018-09-21 16:44
@jlj5aj @sromkey sure, I'll take a look

**Comment by jrwdunham** [comment] 2018-09-21 23:32
@jlj5aj I've also tried to recreate this and have failed. I have not been able to figure out how you managed to get `sip = SIP.objects.get(currentpath=lookup_path).uuid` to *not* raise `SIP.DoesNotExist`. That is, I can't figure out how you can get to this part of the code and already have a `SIP` in the database that corresponds to your transfer. I have tried with AM on both stable/1.7.x and on the current qa branch.

Could you maybe post a screenshot of your processing config decisions? Also, could you let us know if AIP reingest or Transfer Backlog are implicated in any of this?

Note: clearly your fix in PR 1267 is sensible. I'd just like to be able to re-create your issue.

**Comment by jlj5aj** [comment] 2018-09-24 15:19
I am not sure if our config will be helpful as I believe it has changed somewhat since this occurred.  However, looking back, it appears we created two different transfers with this same name around the same time.  The "Create SIP from transfer" step succeeded for the first one on 9/6, while the second one (above) failed on 9/7.  Perhaps that line of code is picking up the earlier transfer?

**Comment by sromkey** [comment] 2018-10-12 20:49
We were having trouble reproducing this to begin with but in any case assigning UUIDs to directories is working as expected. Moving to verified.

**Closed** 2018-11-22 16:06 UTC
Labels: Severity: low, Status: verified, Type: bug
